### ISSUE TITLE
Not Working what do i do

### ISSUE THREAD

**Issue by WizardEli12** [OnlyNoobDied/GadgetsMenu#113]
Hello I'm having trouble with your plugin when I go into the gadgets menu and try to click on something it doesn't work and the same goes with the mystery vault do I need a plugin or something.Please help me I love this plugin and I wanna use it

**Comment by PaulTDD-MC** [comment]
I think this has been confirmed as a bug and the developer is working on it. So it will be patched in the next update :)

**Comment by OnlyNoobDied** [comment]
did you get any errors in console?

**Comment by WizardEli12** [comment]
Yes it said something about it can't load properly because of a mount thing not existing I'll tell you tomorrow

**Comment by WizardEli12** [comment]
here is a error code I found
Plugin GadgetsMenu v3.6.17 has failed to register events for class com.yapzhenyie.GadgetsMenu.listeners.PlayerListeners because org/spigotmc/event/entity/EntityDismountEvent does not exist.

**Comment by WizardEli12** [comment]
and also...
[06:53:56 ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu v3.6.17
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Bukkit-c19c293]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-c19c293]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-c19c293]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-c19c293]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1780) [craftbukkit.jar:git-Bukkit-c19c293]
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [craftbukkit.jar:git-Bukkit-c19c293]
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [craftbukkit.jar:git-Bukkit-c19c293]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-c19c293]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Bukkit-c19c293]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit.jar:git-Bukkit-c19c293]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit.jar:git-Bukkit-c19c293]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit.jar:git-Bukkit-c19c293]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Bukkit-c19c293]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
        at com.yapzhenyie.GadgetsMenu.cosmetics.mainmenu.MainMenuManager.onInvClickMainMenu(MainMenuManager.java:152) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit.jar:git-Bukkit-c19c293]
        ... 15 more

**Comment by OnlyNoobDied** [comment]
you need spigot server to run this plugin. Craftbukkiy server is not
supported.

**Comment by WizardEli12** [comment]
can you make it supported please it would mean a lot to me
