### ISSUE TITLE
Can't edit config?

### ISSUE THREAD

**Issue by Nomiis** [OnlyNoobDied/GadgetsMenu#135]
Hi, i am having problems with editing the config.yml file. When i do it on my host's website (www.minecraft-hosting.pro) it closes instantly, and does not save when pressing the "save" button. I tried downloading the file, and editing with NotePad++, and it saves, but when i upload it onto the FTP of my server, and start the server again, it says:

[19:51:59] [Server thread/ERROR]: Cannot load plugins/GadgetsMenu/config.ymlorg.bukkit.configuration.InvalidConfigurationException: while parsing a block mappingin 'string', line 15, column 5:Gadget-Slot: 8^expected , but found Scalarin 'string', line 18, column 35:Default Pet Name: '&b{PLAYER}'s Pet'^at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at com.yapzhenyie.GadgetsMenu.configuration.FileManager.reload(FileManager.java:213) [GadgetsMenu.jar:?]at com.yapzhenyie.GadgetsMenu.GadgetsMenu.registerConfiguration(GadgetsMenu.java:441) [GadgetsMenu.jar:?]at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:107) [GadgetsMenu.jar:?]at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigotmc-1.11.2-R0.1.jar:git-Spigot-3fb9445-2b6c9f4]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mappingin 'string', line 15, column 5:Gadget-Slot: 8^expected , but found Scalarin 'string', line 18, column 35:Default Pet Name: '&b{PLAYER}'s Pet'^

In console. I have tried saving with UTF-8 with and without BOM, with no luck either.

Thank you.
- Nomiis

**Comment by Nomiis** [comment]
What i want my config file to look like.
[configexample.txt](https://github.com/OnlyNoobDied/GadgetsMenu/files/979931/configexample.txt)

**Comment by PaulTDD-MC** [comment]
Can you send the config.yml after you've changed it? I'll check if you haven't made any spacing errors

**Comment by PaulTDD-MC** [comment]
Try this: https://hastebin.com/esivilifav.vbs

**Comment by Nomiis** [comment]
@PaulTDD-MC Thanks for the reply! The part with the players pet named {Player}'s Pet instead of {Player} Pet worked, but the item (nether star) is still in the 4th (or 5th, can't remember. The default one) slot in the hotbar, and i want it in slot 9, which would be slot 8 in config, since coding works that way. And, MySQL does not work either (I did set it to the correct information.) over my Bungee Network. I might have set MySQL up wrong, since i am not familiar with MySQL, i set it up for the purpose of having this plugin on all servers. Thank you again, your help and time is much appreciated.

- Nomiis

**Comment by Nomiis** [comment]
Wait. About MySQL, should "Database" be set to true in config?

Player-Data:
  Database: false or true?
  MySQL:
    hostname: localhost
    username: root
    database: Database Name
    port: '3306'
    password: Password

**Comment by OnlyNoobDied** [comment]
set it to true.

hotbar slot is starting from 0, until 8.

**Comment by PaulTDD-MC** [comment]
About the nether star. You've set the Gadgets Item to 8 not the Menu Item line 59.
Greetings

**Comment by Nomiis** [comment]
Hi again @PaulTDD-MC, i tried setting Menu Item thingy in line 59 to 8, and set the other one back to 5, and also set Database to true. Which resulted in the plugin breaking so bad, that it went red in /plugins, it's unresponsive and just does not work 😄. Here is the newly edited file:
[configexample.txt](https://github.com/OnlyNoobDied/GadgetsMenu/files/981071/configexample.txt)

**Comment by PaulTDD-MC** [comment]
I will look in to it

**Comment by Nomiis** [comment]
@PaulTDD-MC I have not seen any errors in console no. And i will try disableing the Database tomorrow.

**Comment by Nomiis** [comment]
@PaulTDD-MC Hi! I got everything working, besides MySQL, and for some reason every single tutorial on how to create a MySQL Database is in German. So do you know a way of doing it? :)

**Comment by Nomiis** [comment]
New problem ._. Hostile mobs keep on teleporting into players on our Hub server, but not on our Prison server, and we have the exact same config on each server.

**Comment by Nomiis** [comment]
@PaulTDD-MC @OnlyNoobDied Hi again! One of my staff members apparently knew something about MySQL, and he set one up for us, and he found out, that your plugin does not support the new MariaDB syntax after reading our console errors, which you can find here: https://hastebin.com/raw/ogalezofew

**Comment by OnlyNoobDied** [comment]
okay. give me some time

**Comment by OnlyNoobDied** [comment]
Fixed. This issue will occur when your pet's name contains " ' ".

**Comment by Nomiis** [comment]
Okay, thank you for your time! :)

**Comment by OnlyNoobDied** [comment]
by the way, i haven't upload a fix version

**Comment by OnlyNoobDied** [comment]
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0
