### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drkousek** [OnlyNoobDied/GadgetsMenu#138]
Hi! Error:
[12:53:03] [Server thread/WARN]: [GadgetsMenu] Task #1392 for GadgetsMenu v3.7.0 generated an exception
java.lang.NullPointerException
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.cancel(RewardSystem.java:70) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-65a0347-a552117]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
What can i do?

**Comment by PaulTDD-MC** [comment]
When did this occur?

**Comment by drkousek** [comment]
per one hour

**Comment by drkousek** [comment]
every one hour

**Comment by PaulTDD-MC** [comment]
I mean, does it occur on a specific event of players?

**Comment by drkousek** [comment]
when nothing is at the server

**Comment by OnlyNoobDied** [comment]
i knew what happen. please wait for next update
