### ISSUE TITLE
Tetherball Gadget Error

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#143]
This error occurs when I click Reset All Cosmetics while I have the Tetherball Gadget selected

[02:10:15 ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu v3.7.0
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1094]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1898) ~[patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1094]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1094]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetTetherball.clearAll(GadgetTetherball.java:130) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetTetherball.onClear(GadgetTetherball.java:115) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.api.GadgetAPI.removeGadget(GadgetAPI.java:85) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.api.MainAPI.removeActivatedCosmetics(MainAPI.java:82) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.mainmenu.MainMenuManager.onInvClickMainMenu(MainMenuManager.java:166) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1594.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1094]
        ... 16 more

**Comment by Waffles2112** [comment]
this only happens when i have the tetherball gadget selected, no other gadget

**Comment by OnlyNoobDied** [comment]
Sorry, this bug can't be fix due outdated server version.

**Comment by Waffles2112** [comment]
how is it outdated when its 1.11.2?
thats the latest version :T

**Comment by OnlyNoobDied** [comment]
do you still get error using the latest GadgetsMenu?

**Comment by Waffles2112** [comment]
not anymore
Thnx for fix

**Comment by OnlyNoobDied** [comment]
ok
