### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drkousek** [OnlyNoobDied/GadgetsMenu#145]
Hi! I have next errors: (nothing was on server)
[18:19:28] [Server thread/WARN]: [GadgetsMenu] Task #183 for GadgetsMenu v3.7.0 generated an exception
java.lang.NullPointerException
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.cancel(RewardSystem.java:70) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-65a0347-a552117]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[18:19:29] [Craft Scheduler Thread - 200/INFO]: [1vs1] ***** 1vs1 Version Checker ***** 
[18:19:29] [Craft Scheduler Thread - 200/INFO]: [1vs1] Stable Build: #221
[18:19:29] [Craft Scheduler Thread - 200/INFO]: [1vs1] Current Build: #221
[18:19:29] [Craft Scheduler Thread - 200/INFO]: [1vs1] No new version available
[18:19:29] [Craft Scheduler Thread - 200/INFO]: [1vs1] *********************************
[18:19:31] [Server thread/WARN]: [GadgetsMenu] Task #235 for GadgetsMenu v3.7.0 generated an exception
java.lang.NullPointerException
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.cancel(RewardSystem.java:70) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-65a0347-a552117]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[18:19:45] [Server thread/WARN]: [GadgetsMenu] Task #334 for GadgetsMenu v3.7.0 generated an exception
java.lang.NullPointerException
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.cancel(RewardSystem.java:70) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-65a0347-a552117]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[18:20:57] [Server thread/WARN]: [GadgetsMenu] Task #844 for GadgetsMenu v3.7.0 generated an exception
java.lang.NullPointerException
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.cancel(RewardSystem.java:70) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-65a0347-a552117]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[18:29:54] [Server thread/WARN]: [GadgetsMenu] Task #3634 for GadgetsMenu v3.7.0 generated an exception
java.lang.NullPointerException
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.cancel(RewardSystem.java:70) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-65a0347-a552117]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by OnlyNoobDied** [comment]
fixed.
