### ISSUE TITLE
MobGun Gadget Horse Error

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#146]
I Get this error when I try to use the mob gun with the horse selected, this happens only when horse is selected, and the horses dont despawn, they just sit there:

[14:07:34 ERROR]: Could not pass event PlayerInteractEvent to GadgetsMenu v3.7.0
org.bukkit.event.EventException
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.11.2.jar:git-Paper-1094]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) ~[patched_1.11.2.jar:git-Paper-1094]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) ~[patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:955) ~[patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1094]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1094]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1094]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.UnsupportedOperationException: Not supported.
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftAbstractHorse.setVariant(CraftAbstractHorse.java:26) ~[patched_1.11.2.jar:git-Paper-1094]
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetMobGun.onClick(GadgetMobGun.java:79) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.Gadget$GadgetListener.onPlayerActivateGadget(Gadget.java:174) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.11.2.jar:git-Paper-1094]
        ... 19 more

**Comment by OnlyNoobDied** [comment]
Fixed.
