### ISSUE TITLE
MySQL Database

### ISSUE THREAD

**Issue by Nomiis** [OnlyNoobDied/GadgetsMenu#156]
Hi again!

I installed LibsDisguises onto my server, to get Morphs working, and it did! But at the same time, it made my MySQL non working. I tried a lot of things, i even went as far as reinstalling the plugin fully, but for some bizarre reason, my alt's cosmetics WON'T delete! And i can't get MySQL working again either. The LibsDisguises version i installed was 9.1.3 i belive. I'm just clarifying here, i CANT reset my alts cosmetics, i tried deleted userdata, i tried /gmenu reset all all, and /gmenu reset all "my alts name", and as i said, i even reinstalled the plugin (and deleted the folder), and he still has the cosmetics. I don't know why MySQL is not working, but i assume it's something to do with my alt, since it's him i am testing on.

Thank you!

**Comment by Nomiis** [comment]
I just tested to see if the same problem occured on my main account. MySQL does not work for that account either, i'm not sure about the "can't delete cosmetics" problem.

**Comment by Nomiis** [comment]
Also, i am not seeing anything in console from GadgetMenu.

**Comment by OnlyNoobDied** [comment]
what server version you 're using?

**Comment by PaulTDD-MC** [comment]
@Nomiis, that is an error to do with LibsDisguises. I've had the same problem too. You should report it to that author, not here. Greetings :)

**Comment by Nomiis** [comment]
@OnlyNoobDied I am using spigot 1.11.2, and just now my server died completely, and the MySQL exploded, and now the plugin is red again in /plugins, and does not work at all. And @PaulTDD-MC, about LibsDisguises, i will not be using it. I am pretty sure it's because i was using the latest free version (9.1.3) it broke, since i did not want to pay for it (It costs money now, for 9.3.0 or what version it is now.) I will try to reinstall GadgetsMenu once again, on the server where it's not working.

**Comment by Nomiis** [comment]
Hi, i have tried reinstalling the plugin on my second server now, and it works now, but this came up in console:

[18:02:44] [Server thread/INFO]: [GadgetsMenu] Enabling GadgetsMenu v3.7.2[18:02:45] [Server thread/INFO]: [GadgetsMenu] Required Lib's Disguises plugin to enable morphs![18:03:00] [Server thread/INFO]: [GadgetsMenu] Failed to connect to the database![m[18:03:00] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failureThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.[18:03:00] [Server thread/WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[18:03:00] [Server thread/WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)[18:03:00] [Server thread/WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[18:03:00] [Server thread/WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.java:806)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection.java:47)[18:03:00] [Server thread/WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[18:03:00] [Server thread/WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)[18:03:00] [Server thread/WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[18:03:00] [Server thread/WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)[18:03:00] [Server thread/WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:664)[18:03:00] [Server thread/WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:247)[18:03:00] [Server thread/WARN]: at com.yapzhenyie.GadgetsMenu.mysql.MySQLConnection.openConnection(MySQLConnection.java:36)[18:03:00] [Server thread/WARN]: at com.yapzhenyie.GadgetsMenu.GadgetsMenu.getConnection(GadgetsMenu.java:482)[18:03:00] [Server thread/WARN]: at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:118)[18:03:00] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)[18:03:00] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)[18:03:00] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)[18:03:00] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)[18:03:00] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)[18:03:00] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421)[18:03:00] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382)[18:03:00] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)[18:03:00] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)[18:03:00] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)[18:03:00] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)[18:03:00] [Server thread/WARN]: Caused by: java.net.ConnectException: Connection timed out (Connection timed out)[18:03:00] [Server thread/WARN]: at java.net.PlainSocketImpl.socketConnect(Native Method)[18:03:00] [Server thread/WARN]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)[18:03:00] [Server thread/WARN]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)[18:03:00] [Server thread/WARN]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)[18:03:00] [Server thread/WARN]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)[18:03:00] [Server thread/WARN]: at java.net.Socket.connect(Socket.java:589)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)[18:03:00] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.(MysqlIO.java:300)[18:03:00] [Server thread/WARN]: ... 28 more[18:03:00] [Server thread/INFO]: [GadgetsMenu] Disabling GadgetsMenu v3.7.2

Which i assume means that MySQL is not working, and i don't know why.

**Comment by PaulTDD-MC** [comment]
Well then I don't know...

**Comment by OnlyNoobDied** [comment]
Your mysql database is off?

**Comment by Nomiis** [comment]
It was not. But i decided to switch over to UltraCosmetics, since this plugin gave me so many issues. Sorry.

**Comment by OnlyNoobDied** [comment]
alright then
