### ISSUE TITLE
Morph error please help!!

### ISSUE THREAD

**Issue by paxoboy** [OnlyNoobDied/GadgetsMenu#16]
08:55:25 Could not pass event InventoryClickEvent to GadgetsMenu v3.5.5
08:55:25 org.bukkit.event.EventException
08:55:25 	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.9.2.jar:git-Spigot-2038f4a-cd36f6f]
08:55:25 	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.9.2.jar:git-Spigot-2038f4a-cd36f6f]
08:55:25 	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-2038f4a-cd36f6f]
08:55:25 	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-2038f4a-cd36f6f]
08:55:25 	at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source) ~[?:?]
08:55:25 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
08:55:25 	... 16 more

It dose not even morph the player it gives us an item of the thing we are ment to click on plz help

protocol lib and lib's disguises is already installed and updated

**Comment by OnlyNoobDied** [comment]
Please update your lib's disguises version: https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Morphs

**Comment by paxoboy** [comment]
I have

**Comment by OnlyNoobDied** [comment]
is it the full errors?

**Comment by paxoboy** [comment]
yes that's the errors i posted

**Comment by paxoboy** [comment]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.wrappers.Vector3F
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at me.libraryaddict.disguise.disguisetypes.FlagType.<clinit>(FlagType.java:81) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.Disguise.setupWatcher(Disguise.java:796) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.Disguise.setEntity(Disguise.java:698) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.MobDisguise.setEntity(MobDisguise.java:116) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.MobDisguise.setEntity(MobDisguise.java:12) ~[?:?]
        at me.libraryaddict.disguise.DisguiseAPI.disguiseEntity(DisguiseAPI.java:213) ~[?:?]
        at me.libraryaddict.disguise.DisguiseAPI.disguiseToAll(DisguiseAPI.java:317) ~[?:?]
        at com.OnlyNoobDied.GadgetsMenu.Cosmetics.Morphs.DisguiseManager.disguise(DisguiseManager.java:13) ~[?:?]
        at com.OnlyNoobDied.GadgetsMenu.API.MorphAPI.disguise(MorphAPI.java:53) ~[?:?]
        at com.OnlyNoobDied.GadgetsMenu.Cosmetics.Morphs.MorphManager.onInvClickMorphs(MorphManager.java:244) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        ... 15 more
>

**Comment by OnlyNoobDied** [comment]
you change your spigot version to 1.10?

**Comment by OnlyNoobDied** [comment]
the main problems is you downloaded wrong Lib's Disguises plugin version

**Comment by paxoboy** [comment]
Ok iv done a complete re-install in a new folder it works thanks but it dossent allow the mobs to use their abilities ect

**Comment by OnlyNoobDied** [comment]
i haven't add ability yet.
