### ISSUE TITLE
Exception.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#185]
[23:56:00] [Server thread/WARN]: [GadgetsMenu] Task #160207529 for GadgetsMenu v3.7.4 generated an exception
java.lang.IllegalStateException: Not scheduled yet
	at org.bukkit.scheduler.BukkitRunnable.getTaskId(BukkitRunnable.java:134) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.scheduler.BukkitRunnable.cancel(BukkitRunnable.java:18) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by OnlyNoobDied** [comment]
Fixed. Try this updates
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-11-2.10885/updates
