### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by LasagnaFTW** [OnlyNoobDied/GadgetsMenu#196]
And also, how come de-opped players have to left click to open up the mystery vault?
[07:40:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gmysteryboxes' in plugin GadgetsMenu v3.7.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
        at com.yapzhenyie.GadgetsMenu.utils.Holograms.createHolograms(Holograms.java:45) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.commands.mysterybox.subcommands.CommandMode.onCommandPlayer(CommandMode.java:71) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.commands.mysterybox.CommandManager.onCommand(CommandManager.java:190) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        ... 14 more

**Comment by OnlyNoobDied** [comment]
set 'Spawn-Protect' to 0, then player will able to open mystery vault.

**Comment by OnlyNoobDied** [comment]
can you send me your config file?
