### ISSUE TITLE
Bug with the plugin.

### ISSUE THREAD

**Issue by Dorlomonogo** [OnlyNoobDied/GadgetsMenu#23]
Hey, good day, this is the log!
[20:34:42] [Server thread/INFO]: [GadgetsMenu] Enabling GadgetsMenu v3.5.8
[20:34:42] [Server thread/ERROR]: Error occurred while enabling GadgetsMenu v3.5.8 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.OnlyNoobDied.GadgetsMenu.Utils.MessageType.getFormatMessage(MessageType.java:100) ~[?:?]
	at com.OnlyNoobDied.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:76) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[Spigot-1649.jar:git-Spigot-1649]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [Spigot-1649.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [Spigot-1649.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [Spigot-1649.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [Spigot-1649.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [Spigot-1649.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [Spigot-1649.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [Spigot-1649.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [Spigot-1649.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [Spigot-1649.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot-1649.jar:git-Spigot-1649]
Caused by: java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:206) ~[Spigot-1649.jar:git-Spigot-1649]
	at com.OnlyNoobDied.GadgetsMenu.Utils.ChatUtil.format(ChatUtil.java:8) ~[?:?]
	at com.OnlyNoobDied.GadgetsMenu.API.MainAPI.<clinit>(MainAPI.java:41) ~[?:?]
	... 13 more
[20:34:42] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.2.1

**Comment by OnlyNoobDied** [comment]
1.7 is not supported

**Comment by OnlyNoobDied** [comment]
please use 1.8 or above to run this plugin
