### ISSUE TITLE
bug- Overlapping melody on each other and more bugs

### ISSUE THREAD

**Issue by ProDash1998** [OnlyNoobDied/GadgetsMenu#240]
https://youtu.be/MbWn8UO07K4 - videos show bugs

**Comment by ProDash1998** [comment]
and not add items Do not add item after it has been captured

**Comment by ProDash1998** [comment]
http://imgur.com/a/bnoCX

**Comment by ProDash1998** [comment]
and 
Add to plg (mysql) to work mysterydusty on more sub-servers. Because the quantity is in one mode is eg 100 and in 2 mode is 0

**Comment by OnlyNoobDied** [comment]
I have already knew this issue, so i will remove BoardcastRadioGadget in the next version.

Second thing,
> and not add items Do not add item after it has been captured
> 
> Run-Command: lp user {PLAYER} permission set {PERMISSION}
> Followed by consoles running
> https://youtu.be/nfrbHn1vA9g

> http://imgur.com/a/bnoCX
> He writes to me that I have right click and click the left

> and
> Add to plg (mysql) to work mysterydusty on more sub-servers. Because the quantity is in one mode is eg 100 and in 2 mode is 0

I'm not understand what you want to tell me?

**Comment by ProDash1998** [comment]
This is all about adding a myster dusty to the database not in the file because on server X I have 200 and on server Y I have 0

**Comment by OnlyNoobDied** [comment]
mystery dust is support mysql.  Mystery boxes not supported yet.

**Comment by ProDash1998** [comment]
And where can i find it

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-how-can-i-hook-mystery-dust-to-vaultplayerpointsfile-or-mysql-database

**Comment by ProDash1998** [comment]
`[15:00:56 ERROR]: Could not pass event PlayerInteractEvent to GadgetsMenu v3.7.10
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IllegalStateException: Start block missed in BlockIterator
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:170) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:233) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:268) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:168) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:203) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at com.yapzhenyie.GadgetsMenu.utils.BlockUtil.getTargetBlock(BlockUtil.java:112) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetTeleportStick.checkRequirements(GadgetTeleportStick.java:28) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.Gadget$GadgetListener.onPlayerActivateGadget(Gadget.java:173) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor183.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        ... 17 more
[15:00:56 ERROR]: Could not pass event PlayerInteractEvent to GadgetsMenu v3.7.10
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [hub1.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IllegalStateException: Start block missed in BlockIterator
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:170) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:233) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:268) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:168) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:203) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        at com.yapzhenyie.GadgetsMenu.utils.BlockUtil.getTargetBlock(BlockUtil.java:112) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetTeleportStick.checkRequirements(GadgetTeleportStick.java:28) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.Gadget$GadgetListener.onPlayerActivateGadget(Gadget.java:173) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor183.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
        ... 17 more`

When it comes to choosing a gadget, it crashes

**Comment by OnlyNoobDied** [comment]
You activate a gadget or choosing a new gadget?

**Comment by ProDash1998** [comment]
choosing

**Comment by ProDash1998** [comment]
What is the permissions to buying gadgets

**Comment by OnlyNoobDied** [comment]
There's no permission for player to buy the gadgets. You just need to setup the command in config.

**Comment by ProDash1998** [comment]
http://www25.zippyshare.com/v/Rs2DxXv8/file.html

**Comment by ProDash1998** [comment]
this is screen. Gadgets is off

**Comment by OnlyNoobDied** [comment]
Did you setup the command in config? 
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust
