### ISSUE TITLE
plugins disables

### ISSUE THREAD

**Issue by ProDash1998** [OnlyNoobDied/GadgetsMenu#242]
[13:25:53 ERROR]: Error occurred while enabling GadgetsMenu v3.7.10 (Is it up to date?)
java.lang.NullPointerException: null
        at com.yapzhenyie.GadgetsMenu.updater.UpdaterChecker.<init>(UpdaterChecker.java:34) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.updater.UpdaterManager.checkUpdate(UpdaterManager.java:36) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:208) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[hub1.jar:git-Paper-1179]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [hub1.jar:git-Paper-1179]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [hub1.jar:git-Paper-1179]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [hub1.jar:git-Paper-1179]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [hub1.jar:git-Paper-1179]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [hub1.jar:git-Paper-1179]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [hub1.jar:git-Paper-1179]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [hub1.jar:git-Paper-1179]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [hub1.jar:git-Paper-1179]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [hub1.jar:git-Paper-1179]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

  plugin version: lastes 
Server version 1.12.1

**Comment by ProDash1998** [comment]
Starts with server 15.08 hour 18 (Polish time). And I must have under the last button

**Comment by OnlyNoobDied** [comment]
Please try the new update.
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=180714
