### ISSUE TITLE
Error when give player Mysteryboxes 2 Seconds after firstjoin by API

### ISSUE THREAD

**Issue by pinguinHD** [OnlyNoobDied/GadgetsMenu#244]
[13:38:27] [Craft Scheduler Thread - 7/ERROR]: Cannot load plugins/GadgetsMenu/userdata/1d69021f-6600-40bd-a426-5074ad187c22.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 3, column 1:
    FNrdWxsIEtpbmc=
    ^
could not find expected ':'
 in 'string', line 4, column 1:
    
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.<init>(FileManager.java:49) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.getPlayerDataFile(FileManager.java:105) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.mystery.newbox.MysteryBox.giveMysteryBox(MysteryBox.java:76) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager$3.run(PlayerManager.java:457) [GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 3, column 1:
    FNrdWxsIEtpbmc=
    ^
could not find expected ':'
 in 'string', line 4, column 1:
    
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:530) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	... 12 more
[13:38:27] [Craft Scheduler Thread - 7/ERROR]: Cannot load plugins/GadgetsMenu/userdata/1d69021f-6600-40bd-a426-5074ad187c22.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 3, column 1:
    mcgJSUgTGVnZW5kYXJ5ICUlIEdhZGdld ... 
    ^
could not find expected ':'
 in 'string', line 4, column 1:
    
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.<init>(FileManager.java:49) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.getPlayerDataFile(FileManager.java:105) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.mystery.newbox.MysteryBox.giveMysteryBox(MysteryBox.java:76) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager$3.run(PlayerManager.java:457) [GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 3, column 1:
    mcgJSUgTGVnZW5kYXJ5ICUlIEdhZGdld ... 
    ^
could not find expected ':'
 in 'string', line 4, column 1:
    
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:530) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	... 12 more
[13:38:27] [Craft Scheduler Thread - 10/ERROR]: Cannot load plugins/GadgetsMenu/userdata/1d69021f-6600-40bd-a426-5074ad187c22.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 3, column 1:
    mcgJSUgTGVnZW5kYXJ5ICUlIEdhZGdld ... 
    ^
could not find expected ':'
 in 'string', line 4, column 1:
    
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.<init>(FileManager.java:49) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.getPlayerDataFile(FileManager.java:105) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.mystery.newbox.MysteryBox.giveMysteryBox(MysteryBox.java:76) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager$3.run(PlayerManager.java:457) [GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 3, column 1:
    mcgJSUgTGVnZW5kYXJ5ICUlIEdhZGdld ... 
    ^
could not find expected ':'
 in 'string', line 4, column 1:
    
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:530) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	... 12 more
[13:38:27] [Craft Scheduler Thread - 9/ERROR]: Cannot load plugins/GadgetsMenu/userdata/1d69021f-6600-40bd-a426-5074ad187c22.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 3, column 1:
    mcgJSUgTGVnZW5kYXJ5ICUlIEdhZGdld ... 
    ^
could not find expected ':'
 in 'string', line 4, column 1:
    
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.<init>(FileManager.java:49) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.getPlayerDataFile(FileManager.java:105) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.mystery.newbox.MysteryBox.giveMysteryBox(MysteryBox.java:76) [GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager$3.run(PlayerManager.java:457) [GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 3, column 1:
    mcgJSUgTGVnZW5kYXJ5ICUlIEdhZGdld ... 
    ^
could not find expected ':'
 in 'string', line 4, column 1:
    
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:530) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	... 12 more

**Comment by OnlyNoobDied** [comment]
Can you send me the file of the player.

1d69021f-6600-40bd-a426-5074ad187c22.yml

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
