### ISSUE TITLE
Problem with scoreboard plugin

### ISSUE THREAD

**Issue by LoryWasHere** [OnlyNoobDied/GadgetsMenu#250]
[Scoreboard] Task #20 for Scoreboard v1.4 generated an exception
java.lang.NullPointerException: null
        at com.yapzhenyie.GadgetsMenu.hook.PlaceholderAPI.onPlaceholderRequest(PlaceholderAPI.java:31) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:342) ~[?:?]
        at com.github.rienbijl.Scoreboard.board.Line.next(Line.java:47) ~[?:?]
        at com.github.rienbijl.Scoreboard.board.Board.update(Board.java:117) ~[?:?]
        at com.github.rienbijl.Scoreboard.board.Updater$1.run(Updater.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[jar.jar:git-Spigot-65e8124-963b19c]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [jar.jar:git-Spigot-65e8124-963b19c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [jar.jar:git-Spigot-65e8124-963b19c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [jar.jar:git-Spigot-65e8124-963b19c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [jar.jar:git-Spigot-65e8124-963b19c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [jar.jar:git-Spigot-65e8124-963b19c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]

**Comment by OnlyNoobDied** [comment]
This issue should be fixed in the next update.
