### ISSUE TITLE
Reset Item Can Be Duplicated Unlimited Times

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#276]
**Able to duplicate the item infinite times (i switched from red wool to barrier)**
**works at first, but can get glitched out sometimes**

- reset button stops working
- can be moved around
- dropable when you exit the inventory menu and holding it
- can be done unlimited times to get free barriers

**Here is the error i get when clicking the reset button:**
[16:44:46 ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu v4.0.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1878) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
        at com.yapzhenyie.GadgetsMenu.utils.cosmetics.morphs.LibDisguise.getDisguise(LibDisguise.java:19) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.suits.types.SuitMermaid.onClear(SuitMermaid.java:44) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.suits.SuitManager.unequipHelmet(SuitManager.java:134) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.suits.SuitManager.unequipSuit(SuitManager.java:104) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipSuit(PlayerManager.java:466) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipActiveCosmetics(PlayerManager.java:426) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.menu.menus.MainMenu.onInvClickMainMenu(MainMenu.java:154) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        ... 15 more

**Comment by OnlyNoobDied** [comment]
What's your Lib's Disguise plugin version?

**Comment by xXIOSCARIXx** [comment]
it's the latest version (9.5.0)

**Comment by OnlyNoobDied** [comment]
pm me in spigot.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
same as #274 , #272
