### ISSUE TITLE
Bug Gadget Paintball and worldguard

### ISSUE THREAD

**Issue by Cybertheo** [OnlyNoobDied/GadgetsMenu#295]
The console was spam of error and i think it's the Gadget PaintBall and worldguard are in conflitcs, the error : "Task #269 for GadgetsMenu v4.0.4 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.yapzhenyie.GadgetsMenu.utils.worldguard.FlagUtils
at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetPaintballGun.setToRestore(GadgetPaintballGun.java:201) ~[?:?]
at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetPaintballGun.access$2(GadgetPaintballGun.java:146) ~[?:?]
at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetPaintballGun$1.run(GadgetPaintballGun.java:82) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]"

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
