### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ProDash1998** [OnlyNoobDied/GadgetsMenu#322]
[10:38:03] [Craft Scheduler Thread - 16/WARN]: [GadgetsMenu] Plugin GadgetsMenu v4.0.6 generated an exception while executing task 220
java.lang.NullPointerException: null
	at com.yapzhenyie.GadgetsMenu.player.GPlayer.getPlayerManager(GPlayer.java:25) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.getPlayerManager(GadgetsMenu.java:674) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.mysql.SQLUtils.syncMysteryBoxes(SQLUtils.java:392) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$10(PlayerManager.java:1329) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[hub1.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [hub1.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
