### ISSUE TITLE
Exception in thread "Craft Scheduler Thread - 11"

### ISSUE THREAD

**Issue by Cybertheo** [OnlyNoobDied/GadgetsMenu#325]
[17:12:50] [Craft Scheduler Thread - 11/WARN]: Exception in thread "Craft Scheduler Thread - 11"
[17:12:50] [Craft Scheduler Thread - 11/WARN]: org.apache.commons.lang.UnhandledException: Plugin GadgetsMenu v4.0.7 generated an exception while executing task 85
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
at com.yapzhenyie.GadgetsMenu.player.GPlayer.getPlayerManager(GPlayer.java:25)
at com.yapzhenyie.GadgetsMenu.GadgetsMenu.getPlayerManager(GadgetsMenu.java:672)
at com.yapzhenyie.GadgetsMenu.mysql.SQLUtils.syncMysteryBoxes(SQLUtils.java:392)
at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$10(PlayerManager.java:1329)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
