### ISSUE TITLE
GadgetsMenu stops working with in 5 mins with dedicated server

### ISSUE THREAD

**Issue by ITzD3stiny** [OnlyNoobDied/GadgetsMenu#349]
`[00:16:22 WARN]: [GadgetsMenu] Task #9100 for GadgetsMenu v4.0.8 generated an exception
java.lang.NullPointerException: permission
        at me.lucko.luckperms.bukkit.model.LPPermissible.hasPermission(LPPermissible.java:132) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102) ~[Hub.jar:git-Spigot-e4d4710-e1ebe52]
        at com.yapzhenyie.GadgetsMenu.menu.menus.mysteryboxes.ConfirmOpenMysteryBoxMenu.test(ConfirmOpenMysteryBoxMenu.java:175) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.menu.menus.mysteryboxes.ConfirmOpenMysteryBoxMenu.lambda$0(ConfirmOpenMysteryBoxMenu.java:129) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Hub.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Hub.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Hub.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Hub.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Hub.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Hub.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
`

Not really sure if this has to do with my dedicated server or just java or my hub.jar but its been crashing alot

**Comment by OnlyNoobDied** [comment]
Did you disable some cosmetic items or cosmetics that can be found in mystery boxes?

**Comment by OnlyNoobDied** [comment]
Do you know what's the item player get?

**Comment by ITzD3stiny** [comment]
No i haven't disable anything and i have not changed anything all i did is setup MySQL but even with out MySQL it still stops working after awhile

**Comment by ITzD3stiny** [comment]
oh and for the item was a pet of a baby sheep and he had a halo ring on his head don't know whats that's called, but even when no one is online or even using it, it still crashes and completely stops working

**Comment by OnlyNoobDied** [comment]
This issue 
This issue will be fixed in the next update.
