### ISSUE TITLE
Help D:

### ISSUE THREAD

**Issue by MEXCLAN** [OnlyNoobDied/GadgetsMenu#370]
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/yapzhenyie/GadgetsMenu/GadgetsMenu : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
Caused by: java.lang.UnsupportedClassVersionError: com/yapzhenyie/GadgetsMenu/GadgetsMenu : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_80]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_80]
        at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_80]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        ... 6 more

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-the-plugin-doesnt-load-correctly-and-show-this-errors
