### ISSUE TITLE
Crash on CreeperMorph

### ISSUE THREAD

**Issue by BeneYT** [OnlyNoobDied/GadgetsMenu#398]
If I have the creeper morph and use the ability, my client is crashing.

Here the error code:
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 28.10.17 23:38
Description: Unexpected error

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Float
	at pz.d(SourceFile:104)
	at wn.bN(EntityPlayer.java:2398)
	at avo.d(GuiIngame.java:642)
	at avo.a(GuiIngame.java:183)
	at de.labystudio.minecraft.GuiIngameMod.a(GuiIngameMod.java:572)
	at bfk.a(EntityRenderer.java:1330)
	at ave.av(Minecraft.java:1136)
	at ave.a(Minecraft.java:428)
	at net.minecraft.client.main.Main.main(SourceFile:124)
```

**Comment by OnlyNoobDied** [comment]
Is GuiIngameMod a plugin?

**Comment by OnlyNoobDied** [comment]
This issue caused by Lib's Disguise plugin
