### ISSUE TITLE
Exception.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#403]
[12:14:40] [Craft Scheduler Thread - 2/WARN]: [GadgetsMenu] Plugin GadgetsMenu v4.0.16 generated an exception while executing task 1217
java.lang.NullPointerException: null
	at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesLoot.<init>(MysteryBoxesLoot.java:70) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxes.<init>(MysteryBoxes.java:66) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$14(PlayerManager.java:2123) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by TheIntelloBox** [comment]
Okay nice, thanks.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
