### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#410]
[19:05:14] [Craft Scheduler Thread - 37/ERROR]: Cannot load plugins/GadgetsMenu/userdata/94438733-6214-3bbf-a36d-59997c948f6a.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 2, column 1:
    a36d-59997c948f6a
    ^
could not find expected ':'
 in 'string', line 3, column 1:
    Mystery Dust: 0
    ^
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.<init>(FileManager.java:61) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.configuration.FileManager.getPlayerDataFile(FileManager.java:141) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.initFileData(PlayerManager.java:2115) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.player.GPlayer.initPlayer(GPlayer.java:86) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.listeners.PlayerListener.lambda$0(PlayerListener.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 2, column 1:
    a36d-59997c948f6a
    ^
could not find expected ':'
 in 'string', line 3, column 1:
    Mystery Dust: 0
    ^
	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:424) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	... 13 more

**Comment by OnlyNoobDied** [comment]
Did you modify the file?

**Comment by TheIntelloBox** [comment]
Nop.

**Comment by TheIntelloBox** [comment]
Omg it affects all players so please fix it. :c They lose all their mystery boxes on every reload and disconnect.

**Comment by OnlyNoobDied** [comment]
You give player mystery boxes when they join server?

**Comment by TheIntelloBox** [comment]
No, they have their mystery box by the time of play.

**Comment by TheIntelloBox** [comment]
?

**Comment by TheIntelloBox** [comment]
Please fix it...

**Comment by OnlyNoobDied** [comment]
This issue has been fixed since 4.0.20, but the problem still exist and saved in playerdata.

**Comment by OnlyNoobDied** [comment]
This issue won't happen again.
