### ISSUE TITLE
Task error.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#416]
[23:04:18] [Craft Scheduler Thread - 96/WARN]: [GadgetsMenu] Plugin GadgetsMenu v4.0.21 generated an exception while executing task 73602
java.lang.NullPointerException: null
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.initFileData(PlayerManager.java:2110) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.player.GPlayer.initPlayer(GPlayer.java:86) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.listeners.PlayerListener.lambda$0(PlayerListener.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
