### ISSUE TITLE
Plugin Fails to load due to invalid plugin.yml

### ISSUE THREAD

**Issue by HungryBoy02** [OnlyNoobDied/GadgetsMenu#417]
This error only happens when i make my server run in online mode **(EDIT: Now it happens all the time)**. The plugin fails to load because of an invalid plugin.yml, here is the error:
`[14:20:37 ERROR]: Could not load 'plugins\GadgetsMenu.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:78) ~[server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:751) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:76) ~[server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        ... 21 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_101]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_101]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_101]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_101]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:76) ~[server-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        ... 21 more`

**Comment by OnlyNoobDied** [comment]
Reinstall the plugin

**Comment by HungryBoy02** [comment]
Already tried

**Comment by HungryBoy02** [comment]
Nvm, after the fifth reinstall it worked, my bad

**Comment by OnlyNoobDied** [comment]
Something wrong with the spigot download
