### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ITSRAKRAK10** [OnlyNoobDied/GadgetsMenu#42]
[19:30:08 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.                                   EntityShulker
[19:30:08 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl                                   uginClassLoader.java:91)
[19:30:08 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl                                   uginClassLoader.java:86)
[19:30:08 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[19:30:08 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[19:30:08 WARN]:        at java.lang.Class.forName0(Native Method)
[19:30:08 WARN]:        at java.lang.Class.forName(Class.java:195)
[19:30:08 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager                                   .getNmsClass(ReflectionManager.java:470)
[19:30:08 WARN]:        at me.libraryaddict.disguise.LibsDisguises.onEnable(Libs                                   Disguises.java:79)
[19:30:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlug                                   in.java:321)
[19:30:08 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(                                   JavaPluginLoader.java:340)
[19:30:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(Si                                   mplePluginManager.java:405)
[19:30:08 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin                                   (CraftServer.java:357)
[19:30:08 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlug                                   ins(CraftServer.java:317)
[19:30:08 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(Cra                                   ftServer.java:741)
[19:30:08 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:535)
[19:30:08 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(Rel                                   oadCommand.java:25)
[19:30:08 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo                                   mmandMap.java:141)
[19:30:08 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCo                                   mmand(CraftServer.java:641)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleC                                   ommand(PlayerConnection.java:1162)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(Playe                                   rConnection.java:997)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(Packe                                   tPlayInChat.java:45)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(Packe                                   tPlayInChat.java:1)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.                                   run(SourceFile:13)
[19:30:08 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(E                                   xecutors.java:471)
[19:30:08 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:2                                   62)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile                                   :44)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(Minecr                                   aftServer.java:715)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(Dedica                                   tedServer.java:374)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(Minecr                                   aftServer.java:654)
[19:30:08 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Mine                                   craftServer.java:557)
[19:30:08 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by OnlyNoobDied** [comment]
i think you install wrong Lib's Disguises plugin version.

**Comment by ITSRAKRAK10** [comment]
Ok Can You Dow 1.8 / 1.9 / 1.10 Pliz

**Comment by OnlyNoobDied** [comment]
when using 1.8 spigot, Lib's Disguises plugin will get errors

**Comment by ITSRAKRAK10** [comment]
ok Delete Lib's Disguises?

**Comment by OnlyNoobDied** [comment]
i means Lib's Disguises got errors while running 1.8 server, so i cannot add 1.8 Morphs support.
