### ISSUE TITLE
 my gives me this error, please help :(

### ISSUE THREAD

**Issue by pxndxjhonell** [OnlyNoobDied/GadgetsMenu#45]
[19:47:06 ERROR]: Error occurred while enabling GadgetsMenu v3.5.15 (Is it up to
 date?)
java.lang.NoClassDefFoundError: org/bukkit/entity/Rabbit$Type
        at com.OnlyNoobDied.GadgetsMenu.Utils.Pets.GEntityType.<clinit>(GEntityT
ype.java:14) ~[?:?]
        at com.OnlyNoobDied.GadgetsMenu.Cosmetics.Pets.Types.PetEntityType.<clin
it>(PetEntityType.java:33) ~[?:?]
        at com.OnlyNoobDied.GadgetsMenu.GadgetsMenu.registerListeners(GadgetsMen
u.java:173) ~[?:?]
        at com.OnlyNoobDied.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:79
) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[S
pigot.jar:git-Spigot-da32fe1-2ba7357]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:335) [Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) [Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.jav
a:352) [Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.
java:313) [Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:4
02) [Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:3
70) [Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:3
25) [Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.jav
a:211) [Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:494) [Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Rabbit$Type
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:91) ~[Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86) ~[Spigot.jar:git-Spigot-da32fe1-2ba7357]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        ... 15 more

**Comment by OnlyNoobDied** [comment]
can you try restart your server?If you still get errors, let me know.

**Comment by OnlyNoobDied** [comment]
still get errors?
