### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by DebugingLonks** [OnlyNoobDied/GadgetsMenu#49]
Hi there! Ever since 1.10 I have not been able to load the plugin on my server. I can not figure out why this is, I have been able to run this plugin for a while with no problem but there is all of a sudden...

Oh also in the plugin files i see morphs is supposed to give me a slimeball to use the abilities, but I am not getting the slimeball. 

Thanks for reading!

**Comment by DebugingLonks** [comment]
Heres console log btw

[21:15:03 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/OnlyNoobDied/GadgetsMenu/GadgetsMenu : Unsupported major.minor version 52.0
[21:15:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
[21:15:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[21:15:03 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:353)
[21:15:03 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[21:15:03 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[21:15:03 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:15:03 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:15:03 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:15:03 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:15:03 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[21:15:03 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[21:15:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[21:15:03 WARN]: Caused by: java.lang.UnsupportedClassVersionError: com/OnlyNoobDied/GadgetsMenu/GadgetsMenu : Unsupported major.minor version 52.0
[21:15:03 WARN]:        at java.lang.ClassLoader.defineClass1(Native Method)
[21:15:03 WARN]:        at java.lang.ClassLoader.defineClass(Unknown Source)
[21:15:03 WARN]:        at java.security.SecureClassLoader.defineClass(Unknown Source)
[21:15:03 WARN]:        at java.net.URLClassLoader.defineClass(Unknown Source)
[21:15:03 WARN]:        at java.net.URLClassLoader.access$100(Unknown Source)
[21:15:03 WARN]:        at java.net.URLClassLoader$1.run(Unknown Source)
[21:15:03 WARN]:        at java.net.URLClassLoader$1.run(Unknown Source)
[21:15:03 WARN]:        at java.security.AccessController.doPrivileged(Native Method)
[21:15:03 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[21:15:03 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[21:15:03 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[21:15:03 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[21:15:03 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[21:15:03 WARN]:        at java.lang.Class.forName0(Native Method)
[21:15:03 WARN]:        at java.lang.Class.forName(Unknown Source)
[21:15:03 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
[21:15:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[21:15:03 WARN]:        ... 20 more

I tried with plugman and server restarts, both don't fix.

**Comment by OnlyNoobDied** [comment]
are you sure you are using 1.10?

**Comment by OnlyNoobDied** [comment]
do not using plugman to reload gadgetsmenu plugin, other plugins will get errors.

i haven't add morphs skills, please wait for the next update.

**Comment by DebugingLonks** [comment]
I am using 1.11 right now. This has been an issue since 1.10 however. It says unsupported version sometimes...

**Comment by DebugingLonks** [comment]
Im happy to send a full console boot log or plugin list, its just im trying to set up the lobby for my server lol I used to use UltraCosmetics, but I found this plugin to be much greater :D

**Comment by OnlyNoobDied** [comment]
if you didn't use plugman reload, you still get errors?

**Comment by DebugingLonks** [comment]
Yeah
especialy Unsupported major.minor version 52.0

**Comment by DebugingLonks** [comment]
Ive tried using newest build, tried using old builds.. still nothing

**Comment by OnlyNoobDied** [comment]
i think you're using 1.7 java.

**Comment by DebugingLonks** [comment]
Ill check, but here is the problem i think 

[21:37:56 ERROR]: Could not load 'plugins/GadgetsMenu (4).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/OnlyNoobDied/GadgetsMenu/GadgetsMenu : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:747) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.Bukkit.reload(Bukkit.java:540) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_80]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_80]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
Caused by: java.lang.UnsupportedClassVersionError: com/OnlyNoobDied/GadgetsMenu/GadgetsMenu : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_80]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_80]
        at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_80]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
        ... 21 more

Saying it can't load

**Comment by DebugingLonks** [comment]
Seems I am. Ill restart server, I use server.pro thought it was java 8 lol

**Comment by OnlyNoobDied** [comment]
please use java 8 to run the plugin, because it doesn't support 1.7 java

**Comment by DebugingLonks** [comment]
Looks like it worked loading! Thanks for the help never would have noticed that lol it says successfully loaded, and btw Plugman works for reloading and such, just not loading I used to reload it all the time

**Comment by OnlyNoobDied** [comment]
okay
