### ISSUE TITLE
Does not work correctly Mystery Boxes

### ISSUE THREAD

**Issue by AppleTeams** [OnlyNoobDied/GadgetsMenu#522]
[14:16:42 WARN]: Exception in thread "
[14:16:42 WARN]: Craft Scheduler Thread - 546
[14:16:42 WARN]: "
[14:16:42 WARN]: org.apache.commons.lang.UnhandledException: Plugin GadgetsMenu v4.1.14 generated an exception while executing task 11255
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at com.yapzhenyie.GadgetsMenu.utils.mysteryboxes.CosmeticItems.getRandomItem(CosmeticItems.java:176)
        at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.randomGetCosmeticItem(MysteryBoxesManager.java:128)
        at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.item(MysteryBoxesManager.java:123)
        at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.giveMysteryBoxes(MysteryBoxesManager.java:73)
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$6(PlayerManager.java:1103)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by AppleTeams** [comment]
When I try to give myself out or scrub Mystery Boxes, I do not get a chest ...

**Comment by OnlyNoobDied** [comment]
You do not have any "COMMON" item in your cosmetics.
