### ISSUE TITLE
SQL Bug

### ISSUE THREAD

**Issue by AshStranger** [OnlyNoobDied/GadgetsMenu#528]
数据库没问题，插件正常使用
这个报错是在玩家加入游戏的时候出现的
No problem with the database, the normal use of the plug-in
This error is when the player joins the game
```
[12:27:27 WARN]: java.sql.SQLException: Illegal operation on empty result set.
[12:27:27 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
[12:27:27 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[12:27:27 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[12:27:27 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
[12:27:27 WARN]:        at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:790)
[12:27:27 WARN]:        at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2469)
[12:27:27 WARN]:        at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2580)
[12:27:27 WARN]:        at com.yapzhenyie.GadgetsMenu.mysql.SQLUtils.initStats(SQLUtils.java:69)
[12:27:27 WARN]:        at com.yapzhenyie.GadgetsMenu.player.GPlayer.initPlayer(GPlayer.java:91)
[12:27:27 WARN]:        at com.yapzhenyie.GadgetsMenu.listeners.PlayerListener.lambda$0(PlayerListener.ja
va:35)
[12:27:27 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[12:27:27 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.ja
va:53)
[12:27:27 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:27:27 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:27:27 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:27:27 WARN]: Exception in thread "Craft Scheduler Thread - 5"
[12:27:27 WARN]: org.apache.commons.lang.UnhandledException: Plugin GadgetsMenu v4.1.15 generated an exce
ption while executing task 632
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$4(PlayerManager.java:649)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

```

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
