### ISSUE TITLE
GadgetsMenu Error

### ISSUE THREAD

**Issue by Manu5656** [OnlyNoobDied/GadgetsMenu#554]
Hi, I would like to understand what this mistake means.

`[21:08:32] [Server thread/ERROR]: [GadgetsMenu] Unhandled exception occured in onPacketSending(PacketEvent) for GadgetsMenu
java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$57ac4c2b.getWorld(<generated>) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.hook.protocollib.current.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:78) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.hook.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:130) ~[GadgetsMenu.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.3.0]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:176) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1140) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:371) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:516) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:119) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:104) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:30) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.World.b(World.java:1188) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1186) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1181) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1138) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1099) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:404) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:171) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:63) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:202) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:937) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [PaperSpigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [PaperSpigot.jar:git-Paper-1169]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[21:08:32] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayOutEntityMetadata@779a723b[
    a=6402873
    b=[net.minecraft.server.v1_12_R1.DataWatcher$Item@12bb37f7, net.minecraft.server.v1_12_R1.DataWatcher$Item@26eddfa4, net.minecraft.server.v1_12_R1.DataWatcher$Item@38561a6a, net.minecraft.server.v1_12_R1.DataWatcher$Item@6c5ccc92, net.minecraft.server.v1_12_R1.DataWatcher$Item@27935a61, net.minecraft.server.v1_12_R1.DataWatcher$Item@6f4bb1c8, net.minecraft.server.v1_12_R1.DataWatcher$Item@67466301, net.minecraft.server.v1_12_R1.DataWatcher$Item@6d740b27, net.minecraft.server.v1_12_R1.DataWatcher$Item@508914ba, net.minecraft.server.v1_12_R1.DataWatcher$Item@62fe3a92, net.minecraft.server.v1_12_R1.DataWatcher$Item@36f403a7, net.minecraft.server.v1_12_R1.DataWatcher$Item@7b141b6d, net.minecraft.server.v1_12_R1.DataWatcher$Item@63a0ec71, net.minecraft.server.v1_12_R1.DataWatcher$Item@7019603d, net.minecraft.server.v1_12_R1.DataWatcher$Item@6666aca2, net.minecraft.server.v1_12_R1.DataWatcher$Item@3df21c70, net.minecraft.server.v1_12_R1.DataWatcher$Item@5955bcdb]
  ]`

**Comment by OnlyNoobDied** [comment]
I need to check the code. When I find out the errors I will tell you.

**Comment by OnlyNoobDied** [comment]
It's not GadgetsMenu issue. It might be ProtocolLib compatible issue. I can't do anything with it.
