### ISSUE TITLE
PART─░CLES

### ISSUE THREAD

**Issue by MitterWeaL** [OnlyNoobDied/GadgetsMenu#558]
[04:49:01 ERROR]: Error occurred while enabling GadgetsMenu v4.1.20 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.yapzhenyie.GadgetsMenu.cosmetics.Category.PART─░CLES
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_171]
        at com.yapzhenyie.GadgetsMenu.cosmetics.Category.valueOf(Category.java:1) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.MainMenuType.isEnabled(MainMenuType.java:97) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.MainMenuType.checkEnabled(MainMenuType.java:114) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.initCosmetics(GadgetsMenu.java:555) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:205) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by OnlyNoobDied** [comment]
what country do you lived in?

**Comment by MitterWeaL** [comment]
Turkey.

**Comment by OnlyNoobDied** [comment]
Someone else also report this issue to me before. This issue will be fixed in the next update.

**Comment by MitterWeaL** [comment]
Fast, please.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
