### ISSUE TITLE
Mystery Vault Issue

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#56]
Whenever i restart my server with mystery vaults already set i get this error:
[18:41:37] [Server thread/INFO]: [GadgetsMenu] Enabling GadgetsMenu v3.6.0
[18:41:37] [Server thread/INFO]: [GadgetsMenu] [mChecking for updates...[m
[18:41:38] [Server thread/INFO]: [GadgetsMenu] No update was found, you are running the latest version.[m
[18:41:38] [Server thread/ERROR]: Error occurred while enabling GadgetsMenu v3.6.0 (Is it up to date?)
java.lang.NullPointerException
	at com.OnlyNoobDied.GadgetsMenu.utils.Holograms.createMysteryVaultHolograms(Holograms.java:20) ~[?:?]
	at com.OnlyNoobDied.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:234) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.2.jar:git-Paper-916.1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.10.2.jar:git-Paper-916.1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.2.jar:git-Paper-916.1]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:375) [patched_1.10.2.jar:git-Paper-916.1]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:424) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:389) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:329) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:590) [patched_1.10.2.jar:git-Paper-916.1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[18:41:38] [Server thread/INFO]: [GadgetsMenu] Disabling GadgetsMenu v3.6.0

**Comment by Waffles2112** [comment]
i am running 1.10.2 Paper-Spigot btw

**Comment by Waffles2112** [comment]
Continues to show errors after multiple restarts (like 5)

**Comment by OnlyNoobDied** [comment]
can i have your Mystery Vault file?

**Comment by Waffles2112** [comment]
shore
[Mystery Vault.txt](https://github.com/OnlyNoobDied/GadgetsMenu/files/665657/Mystery.Vault.txt)

**Comment by OnlyNoobDied** [comment]
You recently removed worlds?

**Comment by Waffles2112** [comment]
no i have not removed any worlds

**Comment by OnlyNoobDied** [comment]
Fixed.

**Comment by Waffles2112** [comment]
yey!
