### ISSUE TITLE
Some error on 1.8 server

### ISSUE THREAD

**Issue by JoxesCode** [OnlyNoobDied/GadgetsMenu#562]
This plugin doesn't work on my server!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
logs:
```
[18:11:15 INFO]: [GadgetsMenu] Enabling GadgetsMenu v4.1.17
[18:11:15 ERROR]: Error occurred while enabling GadgetsMenu v4.1.17 (Is it up t
 date?)
java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag
        at com.yapzhenyie.GadgetsMenu.utils.items.InventoryUtils.addItemFlags(I
ventoryUtils.java:1199) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.utils.items.ItemUtils.item(ItemUtils.java
163) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.GadgetsMenuData.<init>(GadgetsMenuData.ja
a:175) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:159
 ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[
pigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoade
.java:335) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManag
r.java:405) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.ja
a:355) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer
java:315) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:
02) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:
70) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:
25) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.ja
a:211) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.jav
:494) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.ItemFlag
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader
java:91) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader
java:86) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-59b08be-0899683]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        ... 15 more
```
I'm going crazy!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by OnlyNoobDied** [comment]
I think the spigot version that you're currently using have some problems.
