### ISSUE TITLE
Can you please help me?

### ISSUE THREAD

**Issue by IslamAbdymazhit** [OnlyNoobDied/GadgetsMenu#564]
Hi!
My name is Islam and I am from Kazakhstan, I apologize for my English.
I'm having an error logging in to the server:

The last packet successfully received from the server was 36,973 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
[10:23:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:23:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:23:04 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:23:04 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[10:23:04 WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[10:23:04 WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[10:23:04 WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
[10:23:04 WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
[10:23:04 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
[10:23:04 WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[10:23:04 WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[10:23:04 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[10:23:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[10:23:04 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
[10:23:04 WARN]: 	at com.yapzhenyie.GadgetsMenu.mysql.query.SelectQuery.execute(SelectQuery.java:46)
[10:23:04 WARN]: 	at com.yapzhenyie.GadgetsMenu.mysql.MySQLManager.lambda$0(MySQLManager.java:142)
[10:23:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[10:23:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[10:23:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:23:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:23:04 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:23:04 WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[10:23:04 WARN]: 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
[10:23:04 WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)
[10:23:04 WARN]: 	... 14 more
[10:23:04 WARN]: java.lang.NullPointerException
[10:23:04 WARN]: 	at com.yapzhenyie.GadgetsMenu.mysql.MySQLManager.lambda$0(MySQLManager.java:143)
[10:23:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[10:23:04 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[10:23:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:23:04 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:23:04 WARN]: 	at java.lang.Thread.run(Thread.java:748)

The ports are open, the database name, user name and password are correct.
I will be very grateful if you will help!

**Comment by IslamAbdymazhit** [comment]
My hosting recommends the following: 
set session wait_timeout=28800;

**Comment by IslamAbdymazhit** [comment]
Now the error has increased:
The last packet successfully received from the server was 479,117 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
[11:25:38 WARN]: 	at sun.reflect.GeneratedConstructorAccessor48.newInstance(Unknown Source)
[11:25:38 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:25:38 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[11:25:38 WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[11:25:38 WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[11:25:38 WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
[11:25:38 WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
[11:25:38 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
[11:25:38 WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[11:25:38 WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[11:25:38 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[11:25:38 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[11:25:38 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
[11:25:38 WARN]: 	at com.yapzhenyie.GadgetsMenu.mysql.query.SelectQuery.execute(SelectQuery.java:46)
[11:25:38 WARN]: 	at com.yapzhenyie.GadgetsMenu.mysql.MySQLManager.lambda$0(MySQLManager.java:142)
[11:25:38 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[11:25:38 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[11:25:38 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:25:38 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:25:38 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:25:38 WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[11:25:38 WARN]: 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
[11:25:38 WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)
[11:25:38 WARN]: 	... 14 more
[11:25:38 WARN]: java.lang.NullPointerException
[11:25:38 WARN]: 	at com.yapzhenyie.GadgetsMenu.mysql.MySQLManager.lambda$0(MySQLManager.java:143)
[11:25:38 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[11:25:38 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[11:25:38 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:25:38 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:25:38 WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in the latest version.
