### ISSUE TITLE
Task issue

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#573]
Every few minutes i get task error in console

```
[21:06:21 WARN]: [GadgetsMenu] Task #84496 for GadgetsMenu v4.1.22 generated an exception
java.lang.NullPointerException: null
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.syncSelectedCosmetics(PlayerManager.java:555) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.listeners.PlayerListener.lambda$2(PlayerListener.java:61) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1512]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1512]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) ~[patched_1.12.2.jar:git-Paper-1512]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1512]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1512]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1512]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]```

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
