### ISSUE TITLE
Another Mystery Vault Issue

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#58]
This error is occurring in the console when a player clicks on the mystery vault, preventing them for using the vault and displaying a message: "An error occurred while attempting to perform this command!"

[00:22:59] [Server thread/WARN]: java.lang.NullPointerException
[00:22:59] [Server thread/WARN]: 	at java.lang.String.replace(Unknown Source)
[00:22:59] [Server thread/WARN]: 	at com.OnlyNoobDied.GadgetsMenu.mystery.newbox.MysteryBoxManager.getLore(MysteryBoxManager.java:159)
[00:22:59] [Server thread/WARN]: 	at com.OnlyNoobDied.GadgetsMenu.mystery.newbox.MysteryBoxManager.openMysteryVaultMenu(MysteryBoxManager.java:89)
[00:22:59] [Server thread/WARN]: 	at com.OnlyNoobDied.GadgetsMenu.listeners.mysterybox.MysteryBoxPreviewListener.onPlayerInteract(MysteryBoxPreviewListener.java:44)
[00:22:59] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2942.execute(Unknown Source)
[00:22:59] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[00:22:59] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[00:22:59] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[00:22:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[00:22:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[00:22:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:496)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:912)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[00:22:59] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:22:59] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740)
[00:22:59] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639)
[00:22:59] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by OnlyNoobDied** [comment]
please upload your config.yml file.

**Comment by Waffles2112** [comment]
[config.zip](https://github.com/OnlyNoobDied/GadgetsMenu/files/665659/config.zip)

**Comment by OnlyNoobDied** [comment]
Fixed

**Comment by Waffles2112** [comment]
yey!
