### ISSUE TITLE
MobGun Gadget

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#586]
When you launch a witch, she is not killed after the explosion

**Comment by Matocolotoe** [comment]
Stacktrace :
`[00:47:43] [Server thread/WARN]: [GadgetsMenu] Task #158 for GadgetsMenu v4.1.22 generated an exception
java.lang.NullPointerException
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at com.yapzhenyie.GadgetsMenu.utils.items.ItemUtils.item(ItemUtils.java:106) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetMobGun$1.run(GadgetMobGun.java:124) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
