### ISSUE TITLE
Async block remove

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#611]
Sometimes when I disable the Ice Walker costume, a snow layer is not removed and you have to right-click it to remove it

Also when the Trampoline gadget ends, the same thing happens but with a wool block and it prints an "Asynchronous block remove" error in the console (I don't have the stacktrace right now)

**Comment by Matocolotoe** [comment]
(This issue also happens when a player changes world while having the gadget rocket active, I think)
Stacktrace :
```[10:36:20] [Craft Scheduler Thread - 270/WARN]: Exception in thread "Craft Scheduler Thread - 270" 
[10:36:20] [Craft Scheduler Thread - 270/WARN]: org.apache.commons.lang.UnhandledException: Plugin GadgetsMenu v4.1.23 generated an exception while executing task 9914
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Asynchronous player tracker update!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:313)
	at net.minecraft.server.v1_8_R3.EntityTracker.a(EntityTracker.java:207)
	at net.minecraft.server.v1_8_R3.EntityPlayer.B(EntityPlayer.java:1041)
	at net.minecraft.server.v1_8_R3.EntityPlayer.updateAbilities(EntityPlayer.java:934)
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setAllowFlight(CraftPlayer.java:1165)
	at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetRocket.clearAll(GadgetRocket.java:308)
	at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetRocket.onClear(GadgetRocket.java:286)
	at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.GadgetManager.unequipGadget(GadgetManager.java:75)
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipGadget(PlayerManager.java:502)
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipActiveCosmetics(PlayerManager.java:412)
	at com.yapzhenyie.GadgetsMenu.listeners.PlayerListener.lambda$1(PlayerListener.java:75)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more```

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
Easier to solve this problem when you post the stacktrace.

**Comment by Matocolotoe** [comment]
Yeah, sorry, couldn't get the first one x)
