### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by AodX** [OnlyNoobDied/GadgetsMenu#613]
Hello, i would like to report this problem
`[22:42:17] [Server thread/INFO]: [GadgetsMenu] Enabling GadgetsMenu v4.2.1
[22:42:17] [Server thread/INFO]: [GadgetsMenu] ------------------------------------------------------
[22:42:17] [Server thread/INFO]: [GadgetsMenu] GadgetsMenu 4.2.1 is loading... [server: git-Spigot-642f6d2-57ab4cf (MC: 1.12.2)]
[22:42:17] [Server thread/INFO]: [GadgetsMenu]                Plugin by Yap Zhen Yie.
[22:42:17] [Server thread/INFO]: [GadgetsMenu]               Date Modified: 12 Nov 2018
[22:42:17] [Server thread/INFO]: [GadgetsMenu]                            
[22:42:17] [Server thread/INFO]: [GadgetsMenu]              Initializing module v1_12_R1
[22:42:17] [Server thread/INFO]: [GadgetsMenu] ------------------------------------------------------
[22:42:17] [Server thread/ERROR]: Error occurred while enabling GadgetsMenu v4.2.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.yapzhenyie.GadgetsMenu.utils.GDyeColor.SILVER
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_191]
	at com.yapzhenyie.GadgetsMenu.utils.GDyeColor.valueOf(GDyeColor.java:1) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.custom.CustomBannerType.<init>(CustomBannerType.java:128) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.custom.CustomBannerType.initCustomBanners(CustomBannerType.java:26) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.initCosmetics(GadgetsMenu.java:589) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:206) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Comment by OnlyNoobDied** [comment]
SILVER color has renamed to LIGHT_GRAY
