### ISSUE TITLE
BUG???

### ISSUE THREAD

**Issue by wangdefa233** [OnlyNoobDied/GadgetsMenu#640]
[09:39:28] [Server thread/WARN]: [GadgetsMenu] Task #7254 for GadgetsMenu v4.3.1 generated an exception
java.lang.IllegalArgumentException: Sound effect entity.firework.twinkle.far does not exist
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftSound.getSoundEffect(CraftSound.java:20) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftWorld.playSound(CraftWorld.java:1325) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at com.yapzhenyie.GadgetsMenu.utils.SoundEffect.playSound(SoundEffect.java:770) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysteryvault.animations.types.NormalAnimation.onUpdateParticleEffect(NormalAnimation.java:141) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysteryvault.animations.types.Animation$1.run(Animation.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by OnlyNoobDied** [comment]
Can you use 1.9.4 server instead of 1.9?
