### ISSUE TITLE
Vault bug

### ISSUE THREAD

**Issue by BeneYT** [OnlyNoobDied/GadgetsMenu#641]
when I want to store the mystery dust in vault there is an error showing up in my console and GadgetsMenu is disabling

`[14:05:49 INFO]: [GadgetsMenu] Enabling GadgetsMenu v4.3.1
[14:05:49 INFO]: [GadgetsMenu] ------------------------------------------------------
[14:05:49 INFO]: [GadgetsMenu] GadgetsMenu 4.3.1 is loading... [server: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)]
[14:05:49 INFO]: [GadgetsMenu]                Plugin by Yap Zhen Yie.
[14:05:49 INFO]: [GadgetsMenu]               Date Modified: 28 Nov 2018
[14:05:49 INFO]: [GadgetsMenu]
[14:05:49 INFO]: [GadgetsMenu]              Initializing module v1_8_R3
[14:05:49 INFO]: [GadgetsMenu] ------------------------------------------------------
[14:05:50 INFO]: [GadgetsMenu] Enabled player relative placeholders with ProtocolLib.
[14:05:50 INFO]: [GadgetsMenu] Failed to hook Vault!
[14:05:50 INFO]: [GadgetsMenu] Disabling GadgetsMenu v4.3.1
[14:05:50 ERROR]: Error occurred while enabling GadgetsMenu v4.3.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:119) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:338) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
`

**Comment by OnlyNoobDied** [comment]
Do you have Vault plugin installed?

**Comment by BeneYT** [comment]
Yes, I have. I have it on the latest version

**Comment by OnlyNoobDied** [comment]
Can you downgrade to the old version as the latest version change the api.
