### ISSUE TITLE
Confirm Open MysteryBox NullPointer

### ISSUE THREAD

**Issue by Peebbong** [OnlyNoobDied/GadgetsMenu#655]
[17:59:21 WARN]: [GadgetsMenu] Task #1463 for GadgetsMenu v4.4.4 generated an exception
java.lang.NullPointerException
        at com.yapzhenyie.GadgetsMenu.menu.menus.mysteryboxes.ConfirmOpenMysteryBoxMenu.sendLootMessage(ConfirmOpenMysteryBoxMenu.java:251) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.menu.menus.mysteryboxes.ConfirmOpenMysteryBoxMenu.lambda$1(ConfirmOpenMysteryBoxMenu.java:188) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by OnlyNoobDied** [comment]
Can I have your `custom loots.yml` file?

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
