### ISSUE TITLE
Task #423916 generated an error when executing

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#656]
Server version : 1.8.8
GadgetsMenu version : 4.3.6 (Free)

This error happened when a player joined the server, I believe he had a suit equipped on him.

```
[23:07:30] [Server thread/WARN]: [GadgetsMenu] Task #423916 for GadgetsMenu v4.3.6 generated an exception
java.lang.NullPointerException
	at com.yapzhenyie.GadgetsMenu.cosmetics.suits.types.Suit$1.run(Suit.java:104) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.

**Comment by Matocolotoe** [comment]
was this a feature ? xd

**Comment by OnlyNoobDied** [comment]
Oops XD

**Comment by Matocolotoe** [comment]
you could've just said "this is not a bug, this is a feature, stacktraces are just decorating characters" XD
