### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by PetteRed65** [OnlyNoobDied/GadgetsMenu#66]
I have downloaded your plugin and, when i start it with my server and placeholderAPI, i get that:
[12:33:06 WARN]: java.io.IOException: No such file or directory
[12:33:06 WARN]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[12:33:06 WARN]:        at java.io.File.createNewFile(File.java:1012)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.createfile(FileManager.java:211)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.get(FileManager.java:134)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.MessageType.getFileMessage(MessageType.java:135)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.MessageType.getFormatMessage(MessageType.java:142)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommand(CommandReload.java:35)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommandConsole(CommandReload.java:27)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.onCommand(CommandManager.java:206)
[12:33:06 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:33:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[12:33:06 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:628)
[12:33:06 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:614)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:397)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:361)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
[12:33:06 WARN]:        at java.lang.Thread.run(Thread.java:745)
[12:33:06 WARN]: java.io.IOException: No such file or directory
[12:33:06 WARN]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[12:33:06 WARN]:        at java.io.File.createNewFile(File.java:1012)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.createfile(FileManager.java:211)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.get(FileManager.java:134)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.MessageType.getFileMessage(MessageType.java:135)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.MessageType.getFormatMessage(MessageType.java:146)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommand(CommandReload.java:35)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommandConsole(CommandReload.java:27)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.onCommand(CommandManager.java:206)
[12:33:06 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:33:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[12:33:06 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:628)
[12:33:06 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:614)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:397)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:361)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
[12:33:06 WARN]:        at java.lang.Thread.run(Thread.java:745)
[12:33:06 WARN]: java.io.IOException: No such file or directory
[12:33:06 WARN]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[12:33:06 WARN]:        at java.io.File.createNewFile(File.java:1012)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.createfile(FileManager.java:211)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.getString(FileManager.java:149)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.api.MainAPI.getPrefix(MainAPI.java:39)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.MessageType.getFormatMessage(MessageType.java:146)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommand(CommandReload.java:35)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommandConsole(CommandReload.java:27)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.onCommand(CommandManager.java:206)
[12:33:06 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:33:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[12:33:06 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:628)
[12:33:06 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:614)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:397)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:361)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
[12:33:06 WARN]:        at java.lang.Thread.run(Thread.java:745)
[12:33:06 INFO]: GadgetsMenu » Reloading plugin...
[12:33:06 INFO]: [GadgetsMenu] Disabling GadgetsMenu v3.6.2
[12:33:06 INFO]: [PlaceholderAPI] Unregistered placeholder hook for placeholder: gadgetsmenu
[12:33:06 WARN]: java.io.IOException: No such file or directory
[12:33:06 WARN]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[12:33:06 WARN]:        at java.io.File.createNewFile(File.java:1012)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.createfile(FileManager.java:211)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.getBoolean(FileManager.java:164)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.api.MainAPI.isDatabaseEnabled(MainAPI.java:78)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.GadgetsMenu.onDisable(GadgetsMenu.java:249)
[12:33:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[12:33:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:353)
[12:33:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.PluginUtil.unload(PluginUtil.java:90)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.PluginUtil.reload(PluginUtil.java:31)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommand(CommandReload.java:37)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommandConsole(CommandReload.java:27)
[12:33:06 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.onCommand(CommandManager.java:206)
[12:33:06 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:33:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[12:33:06 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:628)
[12:33:06 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:614)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:397)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:361)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
[12:33:06 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
[12:33:06 WARN]:        at java.lang.Thread.run(Thread.java:745)
[12:33:08 INFO]: [GadgetsMenu] Enabling GadgetsMenu v3.6.2
[12:33:08 WARN]: java.io.IOException: No such file or directory
[12:33:08 WARN]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[12:33:08 WARN]:        at java.io.File.createNewFile(File.java:1012)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.createfile(FileManager.java:211)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.reload(FileManager.java:201)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.GadgetsMenu.registerConfiguration(GadgetsMenu.java:396)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:103)
[12:33:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[12:33:08 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
[12:33:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.PluginUtil.load(PluginUtil.java:73)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.PluginUtil.load(PluginUtil.java:37)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.PluginUtil.reload(PluginUtil.java:32)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommand(CommandReload.java:37)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommandConsole(CommandReload.java:27)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.onCommand(CommandManager.java:206)
[12:33:08 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:33:08 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[12:33:08 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:628)
[12:33:08 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:614)
[12:33:08 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:397)
[12:33:08 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:361)
[12:33:08 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
[12:33:08 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
[12:33:08 WARN]:        at java.lang.Thread.run(Thread.java:745)
[12:33:08 WARN]: java.io.IOException: No such file or directory
[12:33:08 WARN]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[12:33:08 WARN]:        at java.io.File.createNewFile(File.java:1012)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.createfile(FileManager.java:211)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.configuration.FileManager.save(FileManager.java:192)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.GadgetsMenu.registerConfiguration(GadgetsMenu.java:397)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:103)
[12:33:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[12:33:08 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
[12:33:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.PluginUtil.load(PluginUtil.java:73)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.PluginUtil.load(PluginUtil.java:37)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.utils.PluginUtil.reload(PluginUtil.java:32)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommand(CommandReload.java:37)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.subcommands.CommandReload.onCommandConsole(CommandReload.java:27)
[12:33:08 WARN]:        at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.onCommand(CommandManager.java:206)
[12:33:08 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:33:08 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[12:33:08 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:628)
[12:33:08 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:614)
[12:33:08 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:397)
[12:33:08 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:361)
[12:33:08 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
[12:33:08 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
[12:33:08 WARN]:        at java.lang.Thread.run(Thread.java:745)
and other, please help me

**Comment by PetteRed65** [comment]
And i can.'t use any GUI from the plugin

**Comment by PaulTDD-MC** [comment]
Is ProtocolLib up to date?

**Comment by OnlyNoobDied** [comment]
Fixed

**Comment by PetteRed65** [comment]
Hello Paul, I checked the ProtocolLib version, and is the latest version
(4.2.0). I have Restarted the server, but the GUI does not work yet.

2016-12-23 10:06 GMT+01:00 OnlyNoobDied <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
I found that bug, please wait for the new update.

**Comment by PetteRed65** [comment]
ok, thanks

2016-12-23 10:13 GMT+01:00 OnlyNoobDied <notifications@github.com>:

**Comment by PetteRed65** [comment]
Hi Paul,
I have installed the new version of GadgetsMenu, but i can not use it as
before.
I have founded a new error, i hope you can be useful to find the bug.
ERROR:
[04:23:09 ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu
v3.6.5 org.bukkit.event.EventException at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
~[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
~[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1768)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[?:1.8.0_112] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[?:1.8.0_112] at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
[craftbukkit-1.11.jar:git-Bukkit-c8ff651] at
java.lang.Thread.run(Thread.java:745) [?:1.8.0_112] Caused by:
java.lang.NoSuchMethodError:
org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
at
com.OnlyNoobDied.GadgetsMenu.listeners.cosmetics.SelectItemListener.onPlayerSelectItem(SelectItemListener.java:30)
~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_112] at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
~[?:1.8.0_112] at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[?:1.8.0_112] at java.lang.reflect.Method.invoke(Method.java:498)
~[?:1.8.0_112] at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296)
~[craftbukkit-1.11.jar:git-Bukkit-c8ff651] ... 15 more

2016-12-23 10:43 GMT+01:00 Andrea Pettenuzzo <andreapettenuzzo04@gmail.com>:

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-can-i-run-this-plugin-on-bukkit-server-or-any-other-server

Please use spigot server.
