### ISSUE TITLE
Error /gmenu reload

### ISSUE THREAD

**Issue by Endothelium** [OnlyNoobDied/GadgetsMenu#662]
Can't reload the plugin

```
[16:44:38] [Server thread/INFO]: Edabazz issued server command: /gmenu reload
[16:44:38] [Server thread/INFO]: [GadgetsMenu] Disabling GadgetsMenu v4.3.8
[16:44:38] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder hook for placeholder: gadgetsmenu
[16:44:38] [Server thread/ERROR]: Error occurred while disabling GadgetsMenu v4.3.8 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:413) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:148) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:122) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:105) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.syncSelectedCosmetics(PlayerManager.java:640) ~[GadgetsMenu(2).jar:?]
	at com.yapzhenyie.GadgetsMenu.player.GPlayer.dispose(GPlayer.java:167) ~[GadgetsMenu(2).jar:?]
	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onDisable(GadgetsMenu.java:414) ~[GadgetsMenu(2).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.unload(PluginUtils.java:95) ~[GadgetsMenu(2).jar:?]
	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:36) ~[GadgetsMenu(2).jar:?]
	at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.java:39) ~[GadgetsMenu(2).jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[16:44:38] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327)
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:71)
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:42)
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:37)
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.java:39)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[16:44:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:44:38] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:185)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52)
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.<init>(GadgetsMenu.java:82)
[16:44:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:44:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[16:44:38] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:44:38] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[16:44:38] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[16:44:38] [Server thread/WARN]: 	... 12 more
[16:44:38] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Initial initialization
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:188)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52)
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.<init>(GadgetsMenu.java:82)
[16:44:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:44:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[16:44:38] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:44:38] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[16:44:38] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:323)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[16:44:38] [Server thread/WARN]: 	... 1 more
[16:44:38] [Server thread/WARN]: java.lang.NullPointerException
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:77)
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:42)
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:37)
[16:44:38] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.java:39)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
[16:44:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[16:44:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[16:44:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Run /gmenu reload

**Expected behavior**
Plugin reloaded

 - Server Version: 1.13.2
 - GadgetsMenu Version: 4.3.8

**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by Endothelium** [comment]
The issue is not here with the previous version

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
