### ISSUE TITLE
Teleporter Gadgets Error

### ISSUE THREAD

**Issue by Peebbong** [OnlyNoobDied/GadgetsMenu#663]
[16:45:11 WARN]: [GadgetsMenu] Task #1237 for GadgetsMenu v4.4.6 generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:255) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetTeleporter.lambda$0(GadgetTeleporter.java:100) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
