### ISSUE TITLE
Task exception

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#665]
Spigot : 1.8.8
GadgetsMenu : latest free version

I guess this happened in the worldborder distance thing check when a player switched worlds.

```
[20:32:36] [Server thread/WARN]: [GadgetsMenu] Task #294 for GadgetsMenu v4.3.8 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between FreeBuild and Hub
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.Location.distance(Location.java:439) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at com.yapzhenyie.GadgetsMenu.utils.EntityUtils.getNearbyEntities(EntityUtils.java:16) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetDiscoBall$2.run(GadgetDiscoBall.java:173) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by OnlyNoobDied** [comment]
What! It doesn't make sense.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
