### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by YTHappyPlus** [OnlyNoobDied/GadgetsMenu#672]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/31878663/56358028-5b2e2a00-6218-11e9-9fee-1efbf8503c34.png)
error code:[20:28:27 INFO]: [GadgetsMenu] --------------------------------------------------
[20:28:27 INFO]: [GadgetsMenu] Failed to connect to MySQL database!
[20:28:27 INFO]: [GadgetsMenu] --------------------------------------------------
[20:28:27 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[20:28:27 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:28:27 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[20:28:27 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[20:28:27 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[20:28:27 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[20:28:27 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[20:28:27 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[20:28:27 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[20:28:27 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[20:28:27 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[20:28:27 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239)
[20:28:27 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168)
[20:28:27 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[20:28:27 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[20:28:27 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:28:27 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[20:28:27 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[20:28:27 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[20:28:27 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[20:28:27 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[20:28:27 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[20:28:27 WARN]:        at java.sql.DriverManager.getConnection(Unknown Source)
[20:28:27 WARN]:        at java.sql.DriverManager.getConnection(Unknown Source)
[20:28:27 WARN]:        at com.yapzhenyie.GadgetsMenu.mysql.MySQLConnection.openConnection(MySQLConnection.java:37)
[20:28:27 WARN]:        at com.yapzhenyie.GadgetsMenu.mysql.MySQLManager.init(MySQLManager.java:52)
[20:28:27 WARN]:        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:269)
[20:28:27 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:28:27 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:28:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:28:27 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[20:28:27 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[20:28:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[20:28:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[20:28:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[20:28:27 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[20:28:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[20:28:27 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:28:27 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[20:28:27 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:28:27 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[20:28:27 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[20:28:27 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[20:28:27 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[20:28:27 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[20:28:27 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[20:28:27 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[20:28:27 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[20:28:27 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
[20:28:27 WARN]:        at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
[20:28:27 WARN]:        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
[20:28:27 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
[20:28:27 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186)
[20:28:27 WARN]:        ... 26 more
Please Help me

**Comment by OnlyNoobDied** [comment]
Is your MySQL settings correct in GadgetsMenu config?

**Comment by YTHappyPlus** [comment]
I seeting to 
# This option allows you to set where
# player's data do you want to save.
# 
# Storages: 'file' or 'mysql'.
# 
# If you enable mysql, you need to setup MySQL infos.
Player-Data:
  Storage: mysql
  MySQL:
    hostname: localhost
    username: root
    database: gadget
    port: '3306'
    password: privacy
Cosmetic-Item-Purchase:
  # Set to true allows player to purchase cosmetic items.
  Enabled: true
  # Set the storage where do you want to save mystery dust.
  # Available storages: 'file', 'mysql', 'coins-jasperjh', 'coinsapi', 'playerpoints', 'vault'.
  Mystery-Dust-Storage: mysql

**Comment by OnlyNoobDied** [comment]
Is your MySQL working on any other plugins?

**Comment by YTHappyPlus** [comment]
yes
BungeeFriends, Permssionsex use to MYsql(different schema)

**Comment by OnlyNoobDied** [comment]
May I have the MySQL url? You can copy from BungeeFriends or PermissionsEx plugin.

**Comment by YTHappyPlus** [comment]
pex:  basedir: plugins/PermissionsEx
  backend: sql
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      type: sql
      uri: mysql://localhost/pex
      user: root
      password: secreat
      aliases:
      permissions: pex.permissions
      permissions_inheritance: pex.permissions_inheritance
bungeefreidns
Enable: true
DebugMode: false
Username: root
Password: secreat
Address: localhost:3306
Database: friends
Timezone: 
UseSSL: true
+zpex
database:
  username: root
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  password: secreat
  url: jdbc:sqlite:plugins/zPermissions/zPermissions.db

**Comment by OnlyNoobDied** [comment]
What is the version of your MySQL database, it might outdated.

**Comment by YTHappyPlus** [comment]
8.0.15.0

**Comment by Matocolotoe** [comment]
umm @YTHappyPlus you just gave the password of your mysql database you should talk in private conversation to the plugin owner and delete your message asap

**Comment by OnlyNoobDied** [comment]
Do you have MySQL Installer? If does, please reconfigure MySQL settings.
![2841872c02](https://user-images.githubusercontent.com/13622737/56506733-f3e2e380-6551-11e9-9d3a-e7b4c4d5922a.png)

**Comment by YTHappyPlus** [comment]
Thakns XD I fix it!

**Comment by OnlyNoobDied** [comment]
Great, I'm happy with that too
