### ISSUE TITLE
Reload Command Error

### ISSUE THREAD

**Issue by mckite** [OnlyNoobDied/GadgetsMenu#673]
When Using /gmenu reload CMD:
Plugin reloading not correctly!

[02:11:23 INFO]: KitePro issued server command: /gmenu reload
[02:11:23 INFO]: [GadgetsMenu] Disabling GadgetsMenu v4.4.7
[02:11:26 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialize
d!
[02:11:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
[02:11:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327)
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:71)
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:42)
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:37)
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.jav
a:39)
[02:11:26 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[02:11:26 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.j
ava:361)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[02:11:26 WARN]:        at java.lang.Thread.run(Unknown Source)
[02:11:26 WARN]: Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
[02:11:26 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:183)
[02:11:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60)
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.<init>(GadgetsMenu.java:87)
[02:11:26 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[02:11:26 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[02:11:26 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[02:11:26 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[02:11:26 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[02:11:26 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90)
[02:11:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[02:11:26 WARN]:        ... 12 more
[02:11:26 WARN]: Caused by: java.lang.IllegalStateException: Initial initialization
[02:11:26 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:186)
[02:11:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60)
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.<init>(GadgetsMenu.java:87)
[02:11:26 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[02:11:26 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[02:11:26 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[02:11:26 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[02:11:26 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[02:11:26 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90)
[02:11:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[02:11:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327)
[02:11:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248)
[02:11:26 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[02:11:26 WARN]:        ... 1 more
[02:11:26 WARN]: java.lang.NullPointerException
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:77)
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:42)
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:37)
[02:11:26 WARN]:        at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.jav
a:39)
[02:11:26 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[02:11:26 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.j
ava:361)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[02:11:26 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[02:11:26 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by OnlyNoobDied** [comment]
Do you have two or more than two plugins which named GadgetsMenu?

**Comment by OnlyNoobDied** [comment]
Duplicate GadgetsMenu in plugins folder.

**Comment by mckite** [comment]
No, there are no other plugin folders or files which name contains GadgetsMenu  .

**Comment by OnlyNoobDied** [comment]
No duplicate GadgetsMenu plugin in plugins folder?

**Comment by mckite** [comment]
It occures when AutoSaveWorld plugin is loaded.

**Comment by mckite** [comment]
> No duplicate GadgetsMenu plugin in plugins folder?

no duplications

**Comment by OnlyNoobDied** [comment]
Conflicts with AutoSaveWorld plugin :o

**Comment by mckite** [comment]
Still have the problem, version 4.4.8

 Use /gmenu help 2 to display page 2!

 치장 효과 ? Reloading plugin...
 [GadgetsMenu] Disabling GadgetsMenu v4.4.8
 org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327)
        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:71)
        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:42)
        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:37)
        at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.java:39)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)
 Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:183)
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60)
        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.<init>(GadgetsMenu.java:87)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
        ... 12 more
 Caused by: java.lang.IllegalStateException: Initial initialization
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:186)
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60)
        at com.yapzhenyie.GadgetsMenu.GadgetsMenu.<init>(GadgetsMenu.java:87)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305)
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
        ... 1 more
 java.lang.NullPointerException
        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:77)
        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:42)
        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:37)
        at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.java:39)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)

**Comment by OnlyNoobDied** [comment]
This issue only happened when you have AutoSaveWorld plugin?

**Comment by mckite** [comment]
Yes, it seems conflict with AutoSaveWorld.

**Comment by OnlyNoobDied** [comment]
I can't fix this problem on my side.
