### ISSUE TITLE
Error while executing task 36651

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#685]
Don't know when this happened, but this got printed on the console.

```
[19:19:21] [Craft Scheduler Thread - 702/WARN]: Exception in thread "Craft Scheduler Thread - 702" 
[19:19:21] [Craft Scheduler Thread - 702/WARN]: org.apache.commons.lang.UnhandledException: Plugin GadgetsMenu v4.3.16 generated an exception while executing task 36651
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$6(PlayerManager.java:941)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

Spigot : 1.8.8
GadgetsMenu : 4.3.16

**Comment by OnlyNoobDied** [comment]
Seems like this issue happened when player join the server and immediately leave the server before GadgetsMenu data getting loaded.

**Comment by Matocolotoe** [comment]
Data loading should be interrupted if the player is offline

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.
