### ISSUE TITLE
Let GadgetsMenu store player data using uuid!

### ISSUE THREAD

**Issue by bow9500** [OnlyNoobDied/GadgetsMenu#696]
**Describe the bug**
Please let GadgetsMenu use uuid storage, because my server needs to use uuid storage, using player name storage will cause some strange problems with my server
The following error If I do not understand the error, it is due to the use of playername storage caused by the error
I'm sorry my English is not good.

[01:32:23 WARN]: java.sql.SQLException: Incorrect string value: '\xE8\xBF\xB7\xE8\xB7\xAF...' for column 'Name' at row 1
[01:32:23 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[01:32:23 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[01:32:23 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[01:32:23 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[01:32:23 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[01:32:23 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[01:32:23 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[01:32:23 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[01:32:23 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[01:32:23 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[01:32:23 WARN]:        at com.yapzhenyie.GadgetsMenu.mysql.query.InsertQuery.execute(InsertQuery.java:50)
[01:32:23 WARN]:        at com.yapzhenyie.GadgetsMenu.mysql.SQLUtils.lambda$15(SQLUtils.java:1170)
[01:32:23 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[01:32:23 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[01:32:23 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[01:32:23 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[01:32:23 WARN]:        at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
1.When the player opens the mystery...
2.When give to the player mystery...
3.When the player's GadgetsMenu player data updates...

**Expected behavior**
Let GadgetsMenu store player data using uuid!

**Further Information (please complete the following information):**
 - Server Version: [1.8.9]
 - GadgetsMenu Version: [e.g. 4.4.9]
 - Console stack trace if have.

**Screenshots**
![image](https://user-images.githubusercontent.com/49287036/59979936-1b712d80-9621-11e9-9e79-34e639122aa0.png)
![image](https://user-images.githubusercontent.com/49287036/59980019-8ff89c00-9622-11e9-92e9-02a22a81ae15.png)

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by OnlyNoobDied** [comment]
Can you contact me on spigot?
