### ISSUE TITLE
Pet pathing broken in 1.14.4

### ISSUE THREAD

**Issue by TheMorgander** [OnlyNoobDied/GadgetsMenu#703]
**Describe the bug**
Pets fail to follow the player, and prints a continuous error in the console.

**To Reproduce**
Paper version 1.14.4 Build 135
GadgetsMenu 4.4.18 (Premium)
Occurs when you summon a pet.

**Further Information:**
```
20.07 15:40:28 [Server] WARN [GadgetsMenu] Task #8338 for GadgetsMenu v4.4.18 generated an exception
20.07 15:40:28 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.NavigationAbstract.a(DDD)Lnet/minecraft/server/v1_14_R1/PathEntity;
20.07 15:40:28 [Server] INFO at com.yapzhenyie.GadgetsMenu.nms.v1_14_R1.pets.PlayerFollower.followPlayer(PlayerFollower.java:28) ~[?:?]
20.07 15:40:28 [Server] INFO at com.yapzhenyie.GadgetsMenu.nms.v1_14_R1.NMSManagerImpl.followPlayer(NMSManagerImpl.java:59) ~[?:?]
20.07 15:40:28 [Server] INFO at com.yapzhenyie.GadgetsMenu.cosmetics.pets.Pet$1.run(Pet.java:131) ~[?:?]
20.07 15:40:28 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-135]
20.07 15:40:28 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-135]
20.07 15:40:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-135]
20.07 15:40:28 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-135]
20.07 15:40:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-135]
20.07 15:40:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-135]
```

**Comment by OnlyNoobDied** [comment]
The version of GadgetsMenu you're using is not supported 1.14.4 version. Please update to the latest version.
