### ISSUE TITLE
Exception while executing task 13065

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#706]
This happened when someone used the Spooderman suit, unfortunately I don't have more details :/
```
[13:39:39] [Server thread/WARN]: [GadgetsMenu] Task #13065 for GadgetsMenu v4.3.23 generated an exception
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_201]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_201]
	at com.yapzhenyie.GadgetsMenu.cosmetics.suits.types.SuitSpooderman.onUpdate(SuitSpooderman.java:65) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.suits.types.Suit$1.run(Suit.java:112) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Further Information**
 - Server Version: Spigot 1.8.8
 - GadgetsMenu Version: 4.3.23 (latest)

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
