### ISSUE TITLE
Error during server stoping with Vampire suit

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#708]
**Describe the bug**
When I stop the server with a player connected equiped of Vampire suit, this error (available below) is written. Causes some other issues like multiplication of pets and gadget's blocks not removed in the world, because the plugin can't be stopped correctly.

Thanks :)

**To Reproduce**
1. Equip the vampire suit
2. Stop your server
3. See error

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: [Paper 1.13.2]
 - GadgetsMenu Version: [4.3.24]
 - Console stack trace if have.

> [12:00:19 ERROR]: Error occurred while disabling GadgetsMenu v4.3.24 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:515) ~[patched_1.13.2.jar:git-Paper-642]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:196) ~[patched_1.13.2.jar:git-Paper-642]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:187) ~[patched_1.13.2.jar:git-Paper-642]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:151) ~[patched_1.13.2.jar:git-Paper-642]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTask(CraftScheduler.java:120) ~[patched_1.13.2.jar:git-Paper-642]
at com.yapzhenyie.GadgetsMenu.cosmetics.suits.types.SuitVampire.onClear(SuitVampire.java:45) ~[?:?]
at com.yapzhenyie.GadgetsMenu.cosmetics.suits.SuitManager.unequipHelmet(SuitManager.java:188) ~[?:?]
at com.yapzhenyie.GadgetsMenu.cosmetics.suits.SuitManager.unequipSuit(SuitManager.java:165) ~[?:?]
at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipSuit(PlayerManager.java:499) ~[?:?]
at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipActiveCosmetics(PlayerManager.java:451) ~[?:?]
at com.yapzhenyie.GadgetsMenu.player.GPlayer.dispose(GPlayer.java:167) ~[?:?]
at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onDisable(GadgetsMenu.java:345) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[patched_1.13.2.jar:git-Paper-642]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368) ~[patched_1.13.2.jar:git-Paper-642]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444) ~[patched_1.13.2.jar:git-Paper-642]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431) ~[patched_1.13.2.jar:git-Paper-642]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424) ~[patched_1.13.2.jar:git-Paper-642]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874) ~[patched_1.13.2.jar:git-Paper-642]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by OnlyNoobDied** [comment]
I will discover this problem. If it's an issue, I will release new update
as soon as possible.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
