### ISSUE TITLE
输入/gadgetsmenu reload 重载报错

### ISSUE THREAD

**Issue by 1425115471** [OnlyNoobDied/GadgetsMenu#715]
输入/gadgetsmenu reload 重载报错，报错后插件无法使用。

[09:07:42] [Server thread/INFO]: feifei issued server command: /gadgetsmenu reload
[09:07:42] [Server thread/INFO]: [GadgetsMenu] Disabling GadgetsMenu v4.5.2
[09:07:42] [Server thread/WARN]: java.lang.NullPointerException
[09:07:42] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:57)
[09:07:42] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:42)
[09:07:42] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:37)
[09:07:42] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.java:50)
[09:07:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[09:07:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[09:07:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[09:07:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[09:07:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[09:07:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[09:07:42] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by OnlyNoobDied** [comment]
May I know your buyer name for verification?

**Comment by 1425115471** [comment]
MC_feifei

**Comment by OnlyNoobDied** [comment]
Did you just update the GadgetsMenu plugin and use the reload command without restart the server?

**Comment by OnlyNoobDied** [comment]
Please give me some update about your issue.
