### ISSUE TITLE
Error on spigot 1.8

### ISSUE THREAD

**Issue by cezarlacatus** [OnlyNoobDied/GadgetsMenu#73]
i have this error

cezarlacatus issued server command: /gadgetsmenu
[17:50:45] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gadgetsmenu' in plugin GadgetsMenu v3.6.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NoClassDefFoundError: com/google/gson/stream/JsonWriter
	at com.OnlyNoobDied.GadgetsMenu.nms.v1_8_R1.FancyMessageImpl.toJSONString(FancyMessageImpl.java:80) ~[?:?]
	at com.OnlyNoobDied.GadgetsMenu.nms.v1_8_R1.FancyMessageImpl.send(FancyMessageImpl.java:99) ~[?:?]
	at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.printHelpMessage(CommandManager.java:102) ~[?:?]
	at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.onCommand(CommandManager.java:183) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.stream.JsonWriter
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at com.OnlyNoobDied.GadgetsMenu.nms.v1_8_R1.FancyMessageImpl.toJSONString(FancyMessageImpl.java:80) ~[?:?]
	at com.OnlyNoobDied.GadgetsMenu.nms.v1_8_R1.FancyMessageImpl.send(FancyMessageImpl.java:99) ~[?:?]
	at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.printHelpMessage(CommandManager.java:102) ~[?:?]
	at com.OnlyNoobDied.GadgetsMenu.commands.main.CommandManager.onCommand(CommandManager.java:183) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
	... 14 more

**Comment by OnlyNoobDied** [comment]
Fixed. Please check new update
