### ISSUE TITLE
Crash to reload plugin

### ISSUE THREAD

**Issue by CrisKero** [OnlyNoobDied/GadgetsMenu#759]
When I make any changes to the plugin, the config, and I do a **/gmenu reload** , the plugin crashes.

`[14:40:51 WARN]: java.lang.NullPointerException
[14:40:51 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:36)
[14:40:51 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:29)
[14:40:51 WARN]:        at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.java:42)
[14:40:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:40:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[14:40:51 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[14:40:51 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[14:40:51 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[14:40:51 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[14:40:51 WARN]:        at java.lang.Thread.run(Unknown Source)`

Version: **1.8.8**

**Comment by OnlyNoobDied** [comment]
What is the version of GadgetsMenu you're currently using?

**Comment by CrisKero** [comment]
I am using the latest public version.

**Comment by OnlyNoobDied** [comment]
You can try the latest update.
