### ISSUE TITLE
Tictactoe gadget NPE

### ISSUE THREAD

**Issue by FaberoM** [OnlyNoobDied/GadgetsMenu#772]
**Describe the bug**
Playing tic tac toe causes a null pointer exception.

**To Reproduce**
1. Play tic tac toe
2. See error

**Expected behavior**
No NPE would show up.

**Further Information (please complete the following information):**
 - Server Version: 1.15.2
 - GadgetsMenu Version: 4.5.21

```
java.lang.NullPointerException: null
at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetTicTacToe.onUpdate(GadgetTicTacToe.java:206) ~[?:?]
at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.Gadget$1.run(Gadget.java:77) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-283]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-283]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-283]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
