### ISSUE TITLE
GadgetsMenu is unable to play newer .nbs files (version4)

### ISSUE THREAD

**Issue by FaberoM** [OnlyNoobDied/GadgetsMenu#784]
**Describe the bug**
I tried to add a custom song into Disco ball gadget made with this software which is direct replacement for old discontinued note block studio.
https://opennbs.org/

However when I try to playback .nbs files created with that it gives me this error:
```
[03:43:51 WARN]: [GadgetsMenu] Task #928 for GadgetsMenu v4.5.22 generated an exception
java.lang.NullPointerException: null
at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetDiscoBall$2.run(GadgetDiscoBall.java:157) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-327]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-327]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-327]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-327]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-327]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-327]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

This is probably due to nbs version being 4 and is no longer compatible with version 1 players. The version 4 has huge amount of improvements over the old version 1 .nbs format and I would like to see that supported!

Here is little more info about the version 4 format:
https://opennbs.org/nbs

**To Reproduce**
Use a newer version 4 .nbs file
See the error and no sound comes out.

**Expected behavior**
It would playback the file just fine

**Further Information (please complete the following information):**
 - Server Version: Paper 1.15.2
 - GadgetsMenu Version: 4.5.22

Example version 4 .nbs:
[A song in version 4 format.nbs.zip](https://github.com/OnlyNoobDied/GadgetsMenu/files/4733849/A.song.in.version.4.format.nbs.zip)

**Comment by ZeProf2Code** [comment]
Yes, they should update to the new NoteBlockAPI : https://github.com/koca2000/NoteBlockAPI

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
Please check new updates.
