### ISSUE TITLE
TetherBall issue

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#786]
**Describe the bug**
Sometimes, activating TetherBall doesn't link the chicken and the barrier with a leash. An error is thrown and causes a cooldown ignored / not set.

**To Reproduce**
1. Activate several times the gadget TetherBall until the issue occurs...

**Expected behavior**
The chicken should be linked to the barrier and the coodown correctly set. The stacktrace shouldn't appear of course x)

**Further Information (please complete the following information):**
 - Server Version: Paper 1.13.2
 - GadgetsMenu Version: 4.5.22

```[14:20:35 ERROR]: Could not pass event PlayerInteractEvent to GadgetsMenu v4.5.22
java.lang.IllegalStateException: Unable to get CCW facing of up
at net.minecraft.server.v1_13_R2.EnumDirection.f(EnumDirection.java:121) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.EntityHanging.calculateBoundingBox(EntityHanging.java:56) ~[patched_1.13.2.jar:git-Paper-654]
at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.createEntity(CraftWorld.java:1379) ~[patched_1.13.2.jar:git-Paper-654]
at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.spawn(CraftWorld.java:1466) ~[patched_1.13.2.jar:git-Paper-654]
at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.spawn(CraftWorld.java:1072) ~[patched_1.13.2.jar:git-Paper-654]
at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.spawnEntity(CraftWorld.java:417) ~[patched_1.13.2.jar:git-Paper-654]
at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetTetherball.onClick(GadgetTetherball.java:86) ~[?:?]
at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.Gadget$GadgetListener.onPlayerActivateGadget(Gadget.java:217) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-654]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.13.2.jar:git-Paper-654]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-654]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-654]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1348) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-654]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-654]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-654]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by OnlyNoobDied** [comment]
This gadget isn't working in newer minecraft version 1.14/1.15 or above. You're using the latest update of 1.13.2 paper spigot, so you might needed to disable this gadget.

**Comment by Aurelien30000** [comment]
Even in 1.13.2 ? In this case you should automatically disable it like with 1.14+ :p

**Comment by OnlyNoobDied** [comment]
I did disable Tetherball gadget in 1.14 and above but for the older 1.13 version, it is working fine.
