### ISSUE TITLE
Pulling any item out of Gadget Menu bug

### ISSUE THREAD

**Issue by hazycraft** [OnlyNoobDied/GadgetsMenu#79]
I also found out that you can take any item out of the menus by opening gadgets menu then press shift+right click any item then  immediately press e to close the gadgets menu. A major bug that needs to be fixed asap.

here's youtube video i made that shows pulling items out of gadgets menu:
https://www.youtube.com/watch?v=QN_FDR3aalM

Also can you please look into this error that I get every time the server is shutting down. It appears the remove holograms in gadgetsmenu is throwing an error?

[code]
[13:09:09 INFO]: [PlaceholderAPI] Unregistered placeholder hook for placeholder: gadgetsmenu
[13:09:09 ERROR]: Error occurred while disabling GadgetsMenu v3.6.14 (Is it up to date?)
java.lang.NullPointerException
    at com.yapzhenyie.GadgetsMenu.api.MainAPI.getKeys(MainAPI.java:563) ~[?:?]
    at com.yapzhenyie.GadgetsMenu.utils.Holograms.forceRemoveHolograms(Holograms.java:84) ~[?:?]
    at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onDisable(GadgetsMenu.java:285) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
    at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:344) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
    at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:462) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:610) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[/code]

**Comment by OnlyNoobDied** [comment]
can i test it on your server? give me your server ip

**Comment by hazycraft** [comment]
play.hazycraft.com

**Comment by OnlyNoobDied** [comment]
okay, i tested on your server. If you press shift+right click any item then immediately press 'e' to close the gadgets menu it will give you the item you click, but you cannot use it. If you rejoin the server, it will disappear

**Comment by OnlyNoobDied** [comment]
![2017-01-11_16 06 26](https://cloud.githubusercontent.com/assets/13622737/21840349/0589f08e-d818-11e6-885c-5122f3489aca.png)
Example.

**Comment by hazycraft** [comment]
Ok ok after some testing your somewhat right. You cant craft with it or put saddles on horses but what I did find out is you can abuse saddles on pigs = https://youtu.be/rvBNrNS3-zA

**Comment by OnlyNoobDied** [comment]
ok
