### ISSUE TITLE
GadgetsMenu 4.5.27 is not compatible with PAPI 2.10.7

### ISSUE THREAD

**Issue by FaberoM** [OnlyNoobDied/GadgetsMenu#794]
**Describe the bug**
PlaceholderAPI just recently updated their plugin to version 2.10.7 which has new API that drops support for all old depricated methods. Currently plugin throws this error when disabling the plugin:

`[22:34:40 ERROR]: Error occurred while disabling GadgetsMenu v4.5.27 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean me.clip.placeholderapi.PlaceholderAPI.unregisterPlaceholderHook(java.lang.String)'
at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onDisable(GadgetsMenu.java:440) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-366]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Paper-366]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-366]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.15.2.jar:git-Paper-366]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.15.2.jar:git-Paper-366]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:406) ~[patched_1.15.2.jar:git-Paper-366]
at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:749) ~[patched_1.15.2.jar:git-Paper-366]
at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:753) ~[patched_1.15.2.jar:git-Paper-366]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:1016) ~[patched_1.15.2.jar:git-Paper-366]
at java.lang.Thread.run(Thread.java:832) [?:?]`

**To Reproduce**
1. Use GadgetsMenu 4.5.27 in conjunction with PAPI 2.10.7
2. Shutdown the server

**Expected behavior**
No errors would show up

**Further Information (please complete the following information):**
 - Server Version: Paper 1.15.2
 - GadgetsMenu Version: 4.5.27

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
PlaceholderAPI has released new update for legacy api compatible, you can update PAPI plugin. I will release new update when I'm free.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
