### ISSUE TITLE
Console error spam

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#798]
**Describe the bug**
Sometimes, this stacktrace is written in the console : 

```
[14:51:04] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu v4.5.29
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 36
	at java.util.Arrays$ArrayList.get(Arrays.java:4351) ~[?:?]
	at net.minecraft.server.v1_16_R2.NonNullList.get(SourceFile:46) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.PlayerInventory.getItem(PlayerInventory.java:541) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at com.yapzhenyie.GadgetsMenu.listeners.cosmetics.SelectItemListener.onPlayerClickItem(SelectItemListener.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor314.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2431) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1190) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1183) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1320) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Tuinity-"7984e59"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
- Sadly I don't know anymore, this issue seems impossible to reproduce with "steps" :/

**Expected behavior**
No error.

Thanks for your help, I'll try to get more information.

**Further Information (please complete the following information):**
 - Server Version: Tuinity version git-Tuinity-"7984e59" (MC: 1.16.2)
 - GadgetsMenu Version: 4.5.29 [Premium]
 - Console stack trace if have. -> _Error above_

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
