### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xXPitch13Xx** [OnlyNoobDied/GadgetsMenu#8]
[23:12:56 ERROR]: Could not pass event PlayerInteractEvent to GadgetsMenu v3.4.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        at com.OnlyNoobDied.GadgetsMenu.Utils.ChatUtil.format(ChatUtil.java:8) ~[?:?]
        at com.OnlyNoobDied.GadgetsMenu.Cosmetics.Gadgets.Types.GadgetParachute.gadgetParachute(GadgetParachute.java:83) ~[?:?]
        at com.OnlyNoobDied.GadgetsMenu.Cosmetics.Gadgets.Types.GadgetParachute.onPlayerClickGadgetParachute(GadgetParachute.java:62) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.7.jar:git-Spigot-e6f93f4-22dcde5]
        ... 17 more

**Comment by OnlyNoobDied** [comment]
i'm thinking why you using 1.8.7 spigot running v1_9_R1 :/

**Comment by OnlyNoobDied** [comment]
Please update your server to the latest Java version.

**Comment by OnlyNoobDied** [comment]
Please  update your spigot version to 1.8.8 or 1.10.2.

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-9-1-10.10885/

new version released.
