### ISSUE TITLE
I could not start Gadgetmenu for paper 1.16.2 (with the latest PlaceholderAPI version)

### ISSUE THREAD

**Issue by AnLan1214090013** [OnlyNoobDied/GadgetsMenu#804]
[20:00:49] [Craft Scheduler Thread - 7/ERROR]: Error occurred while disabling GadgetsMenu v4.5.30 (Is it up to date?)
java.lang.IllegalStateException: ExpansionUnregisterEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.16.2.jar:git-Paper-185]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.unregister(LocalExpansionManager.java:252) ~[?:?]
	at me.clip.placeholderapi.expansion.PlaceholderExpansion.unregister(PlaceholderExpansion.java:141) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onDisable(GadgetsMenu.java:451) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-185]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-185]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-185]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:508) ~[patched_1.16.2.jar:git-Paper-185]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at com.yapzhenyie.GadgetsMenu.tasks.WorldGuardRegion.run(WorldGuardRegion.java:90) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-185]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-185]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-185]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by OnlyNoobDied** [comment]
Are you a premium buyer?

**Comment by VanillaChan6571** [comment]
I am also getting this message & using the free version. It was fine on 1.16.2 but when going to 1.16.3 caused an issue. Only way bypass is going lower version or resetting your entire config.

**Comment by OnlyNoobDied** [comment]
Only cracked plugin will get this error, which means you're not a buyer of GadgetsMenu premium.
