### ISSUE TITLE
Cannot receive mystery boxes

### ISSUE THREAD

**Issue by NoobiousMcNoob** [OnlyNoobDied/GadgetsMenu#806]
After executing /gmysteryboxes give [player] 1 the console returns `GadgetsMenu >You've successfully gave 1 mystery boxes to [player].` and this error shows up:
` Exception in thread "
[12:48:39 WARN]: Craft Scheduler Thread - 25
[12:48:39 WARN]: "
[12:48:39 WARN]: org.apache.commons.lang.UnhandledException: Plugin GadgetsMenu v4.5.30 generated an exception while executing task 376
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Unknown Source)
        at com.yapzhenyie.GadgetsMenu.utils.mysteryboxes.CosmeticItems.getRandomItem(CosmeticItems.java:62)
        at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.randomGetCosmeticItem(MysteryBoxesManager.java:85)
        at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.item(MysteryBoxesManager.java:80)
        at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.giveMysteryBoxes(MysteryBoxesManager.java:26)
        at com.yapzhenyie.GadgetsMenu.player.OfflinePlayerManager.lambda$0(OfflinePlayerManager.java:129)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)`

**To Reproduce**
1. Gmenu newest version
2. /gmysterybox give [player] 1

**Expected behavior**
I SHOULD GET A BOX

**Further Information (please complete the following information):**
 - Server Version: This server is running CraftBukkit version git-PaperSpigot-f6fba00-9935adc (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
 - GadgetsMenu Version: GadgetsMenu version 4.5.30

**Comment by OnlyNoobDied** [comment]
1. Check your `mysteryboxes.yml` file `Loot-Can-Be-Found` section, make sure all value set to `true`
2. Check your `config.yml` file `Disabled-Cosmetics` section, make sure all value set to `false`

**Comment by OnlyNoobDied** [comment]
Solved
