### ISSUE TITLE
Error in plugin launch

### ISSUE THREAD

**Issue by mani1232** [OnlyNoobDied/GadgetsMenu#807]
**Describe the bug**
[13:30:42] [Craft Scheduler Thread - 3/INFO]: [GadgetsMenu] Disabling GadgetsMenu v4.5.30
[13:30:42] [Craft Scheduler Thread - 3/ERROR]: Error occurred while disabling GadgetsMenu v4.5.30 (Is it up to date?)
java.lang.IllegalStateException: ExpansionUnregisterEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.16.3.jar:git-Paper-202]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.unregister(LocalExpansionManager.java:252) ~[?:?]
	at me.clip.placeholderapi.expansion.PlaceholderExpansion.unregister(PlaceholderExpansion.java:141) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onDisable(GadgetsMenu.java:451) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:508) ~[patched_1.16.3.jar:git-Paper-202]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.tasks.WorldGuardRegion.run(WorldGuardRegion.java:90) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-202]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**To Reproduce**
start server

**Expected behavior**
Plugin launch

**Further Information (please complete the following information):**
 - Server Version: 1.16.3
 - GadgetsMenu Version: 4.5.30

**Screenshots**
-

**Additional Information**
-

**Comment by OnlyNoobDied** [comment]
@mani1232 I need the evidence of GadgetsMenu purchase.

**Comment by OnlyNoobDied** [comment]
Support is only provided to buyers.
