### ISSUE TITLE
Plugin attempts to drop items async

### ISSUE THREAD

**Issue by mikroskeem** [OnlyNoobDied/GadgetsMenu#808]
**Describe the bug**
Plugin attempts to drop items async.

```
[15:46:03 WARN]: [GadgetsMenu] Plugin GadgetsMenu v4.5.30 generated an exception while executing task 59229
java.lang.IllegalStateException: Asynchronous entity add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.3.jar:git-Paper-197]
        at net.minecraft.server.v1_16_R2.WorldServer.addEntity0(WorldServer.java:1146) ~[patched_1.16.3.jar:git-Paper-197]
        at net.minecraft.server.v1_16_R2.WorldServer.addEntity(WorldServer.java:1083) ~[patched_1.16.3.jar:git-Paper-197]
        at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.dropItem(CraftWorld.java:750) ~[patched_1.16.3.jar:git-Paper-197]
        at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.dropItemNaturally(CraftWorld.java:763) ~[patched_1.16.3.jar:git-Paper-197]
        at com.yapzhenyie.GadgetsMenu.cosmetics.emotes.EmoteType.equip(EmoteType.java:527) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipEmote(PlayerManager.java:765) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$4(PlayerManager.java:1151) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-197]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-197]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-197]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**To Reproduce**
1. Set `Settings.Equip-Cosmetic-Item-To-Slot` to `DROP`
2. Apply an emote
3. See error

**Expected behavior**
This error not to pop up

**Further Information (please complete the following information):**
 - Server Version: Paper 1.16.3, build 197
 - GadgetsMenu Version: 4.5.30

**Additional Information**

You should schedule a synchronous task to drop the item.

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
