### ISSUE TITLE
No perm. players

### ISSUE THREAD

**Issue by KuramaMD** [OnlyNoobDied/GadgetsMenu#85]
Players with no permission can access gadgets menu and click on things. 
After they click I get an error in chat
An error occured when executing this command!

And in console
[16:07:21 INFO]: AquaCoon issued server command: /gadgetsmenu main
[16:07:23 WARN]: java.lang.NullPointerException
[16:07:23 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.particles.ParticleManager.openParticlesMenu(ParticleManager.java:75)
[16:07:23 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.mainmenu.MainMenuManager.selectItem(MainMenuManager.java:252)
[16:07:23 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.mainmenu.MainMenuManager.onInvClickMainMenu(MainMenuManager.java:194)
[16:07:23 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:07:23 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:07:23 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:07:23 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[16:07:23 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:07:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:07:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:07:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:07:23 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[16:07:23 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[16:07:23 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[16:07:23 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:07:23 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:07:23 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:07:23 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:07:23 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:07:23 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:07:23 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:07:23 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:07:23 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by OnlyNoobDied** [comment]
please send config file to me

2017年1月22日 10:12 PM，"KuramaMD" <notifications@github.com>写道：

**Comment by KuramaMD** [comment]
http://pastebin.com/vcub7sr5

**Comment by OnlyNoobDied** [comment]
fixed
