### ISSUE TITLE
aqui esta el error no puedo ver los menus los usuarios normales

### ISSUE THREAD

**Issue by xXMasterCrackXx** [OnlyNoobDied/GadgetsMenu#87]
[01:44:13 WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[01:44:13 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.GadgetManager.openGadgetsMenu(GadgetManager.java:93)
[01:44:13 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.mainmenu.MainMenuManager.selectItem(MainMenuManager.java:258)
[01:44:13 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.mainmenu.MainMenuManager.onInvClickMainMenu(MainMenuManager.java:194)
[01:44:13 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:44:13 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:44:13 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:44:13 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[01:44:13 WARN]:        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116)
[01:44:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:44:13 WARN]:        at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28)
[01:44:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[01:44:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[01:44:13 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[01:44:13 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[01:44:13 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[01:44:13 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[01:44:13 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[01:44:13 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[01:44:13 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[01:44:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[01:44:13 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[01:44:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[01:44:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[01:44:13 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by OnlyNoobDied** [comment]
please give me your config

**Comment by Waffles2112** [comment]
'Here is the error I can not see the normal users menus'
is what the title says by the way

**Comment by OnlyNoobDied** [comment]
please send me the config

**Comment by Waffles2112** [comment]
hes a spanish speaker obviously
he doesnt know what that means

**Comment by Waffles2112** [comment]
xXMasterCrackXx
Envíanos la config por favor.

**Comment by Waffles2112** [comment]
and mr. Author, you shouldn't be so quick to close these issues, we understand that you want to get them solved, but your impatience is getting the best of you.
These people can either live in different timezones, so they may not be able to instantly respond.
Also keep in mind that these other people have lives, you need to give them time to respond, for all you know he could be half way around the world, pulling all-nighters  in collage and may not have the time to respond.

**Comment by OnlyNoobDied** [comment]
i think #86 same as #87 so i close issue #86

**Comment by Waffles2112** [comment]
seems legit
ill ask him for his config again

**Comment by Waffles2112** [comment]
xXMasterCrackXx
Envíanos la config por favor.
