### ISSUE TITLE
Not working properly on AdvancedSlimePaper

### ISSUE THREAD

**Issue by BingYanchi** [OnlyNoobDied/GadgetsMenu#946]
**Describe the bug**
The mystery vault hologram cannot be generated, and pets, minions, etc. do not work

**To Reproduce**
1. Run on 1.19.3
2. See error

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: 1.19.3
 - GadgetsMenu Version: 5.3.1
 - Console stack trace if have.

**Screenshots**

```
[07:08:34 INFO]: UUID of player Bing_Yanchi is 186dfa0d-8e66-4302-80a9-110bd79464b5
[07:08:35 INFO]: Bing_Yanchi[/49.65.234.199:50466] logged in with entity id 230 at ([MainLobby]0.3213287684049531, 100.0, 0.2699419775454889)
[07:08:36 INFO]: [FastLogin] Player info LOGIN command for Bing_Yanchi from proxy
[07:08:36 INFO]: [FastLogin] Delaying force login until join event fired?: false
[07:08:37 WARN]: java.lang.NoSuchFieldException: entityLookup
[07:08:37 WARN]:        at java.base/java.lang.Class.getDeclaredFieldImpl(Native Method)
[07:08:37 WARN]:        at java.base/java.lang.Class.getDeclaredFieldInternal(Class.java:940)
[07:08:37 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:915)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getField(ReflectionUtils.java:345)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_19_R2.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:389)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_19_R2.NMSManagerImpl.spawnNMSArmorStand(NMSManagerImpl.java:147)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.mysteryvault.MysteryVault.createIndividualHologram(MysteryVault.java:200)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.mysteryvault.MysteryVault.refreshIndividualHologram(MysteryVault.java:214)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.tasks.UpdateIndividualHologram.run(UpdateIndividualHologram.java:32)
[07:08:37 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[07:08:37 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488)
[07:08:37 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1412)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1188)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[07:08:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:889)
[07:08:37 WARN]: [GadgetsMenu] Could not spawn mystery vault hologram!
[07:08:37 WARN]: java.lang.NoSuchFieldException: entityLookup
[07:08:37 WARN]:        at java.base/java.lang.Class.getDeclaredFieldImpl(Native Method)
[07:08:37 WARN]:        at java.base/java.lang.Class.getDeclaredFieldInternal(Class.java:940)
[07:08:37 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:915)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getField(ReflectionUtils.java:345)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_19_R2.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:389)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_19_R2.NMSManagerImpl.spawnNMSArmorStand(NMSManagerImpl.java:147)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.mysteryvault.MysteryVault.createHolograms(MysteryVault.java:156)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.tasks.UpdateHolograms.run(UpdateHolograms.java:36)
[07:08:37 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[07:08:37 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488)
[07:08:37 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1412)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1188)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[07:08:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:889)
[07:08:37 WARN]: [GadgetsMenu] Could not spawn mystery vault hologram!
[07:08:37 WARN]: java.lang.NoSuchFieldException: entityLookup
[07:08:37 WARN]:        at java.base/java.lang.Class.getDeclaredFieldImpl(Native Method)
[07:08:37 WARN]:        at java.base/java.lang.Class.getDeclaredFieldInternal(Class.java:940)
[07:08:37 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:915)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getField(ReflectionUtils.java:345)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_19_R2.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:389)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_19_R2.NMSManagerImpl.spawnNMSArmorStand(NMSManagerImpl.java:147)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.mysteryvault.MysteryVault.createHolograms(MysteryVault.java:159)
[07:08:37 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.tasks.UpdateHolograms.run(UpdateHolograms.java:36)
[07:08:37 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[07:08:37 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488)
[07:08:37 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1412)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1188)
[07:08:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[07:08:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:889)
[07:08:37 WARN]: [GadgetsMenu] Could not spawn mystery vault hologram!
[07:10:08 WARN]: java.lang.NoSuchFieldException: entityLookup
[07:10:08 WARN]:        at java.base/java.lang.Class.getDeclaredFieldImpl(Native Method)
[07:10:08 WARN]:        at java.base/java.lang.Class.getDeclaredFieldInternal(Class.java:940)
[07:10:08 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:915)
[07:10:08 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getField(ReflectionUtils.java:345)
[07:10:08 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_19_R2.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:389)
[07:10:08 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_19_R2.NMSManagerImpl.spawnNMSMiniature(NMSManagerImpl.java:228)
[07:10:08 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.miniatures.types.Miniature.lambda$new$0(Miniature.java:55)
[07:10:08 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[07:10:08 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[07:10:08 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488)
[07:10:08 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[07:10:08 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1412)
[07:10:08 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1188)
[07:10:08 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[07:10:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:889)
[07:10:08 WARN]: [GadgetsMenu] Could not spawn GadgetsMenu miniature!
```

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by yapzhenyie** [comment]
May I know which server you are using? Either paper/spigot or any other fork?

**Comment by BingYanchi** [comment]
> May I know which server you are using? Either paper/spigot or any other fork?

https://github.com/InfernalSuite/AdvancedSlimePaper

**Comment by yapzhenyie** [comment]
I have tested in my server and seems this issue only happen in ASW world. I will look for the solution and try to fix it in the next update.

**Comment by BingYanchi** [comment]
how is it now?

**Comment by yapzhenyie** [comment]
> how is it now?

Unfortunately, I am unable to fix this issue. This issue seems a bit weird, it only occurs in ASW world, for normal minecraft world it works fine.

**Comment by BingYanchi** [comment]
Still present in AdvancedSlimePaper 1.20.1

**Comment by yapzhenyie** [comment]
> Still present in AdvancedSlimePaper 1.20.1

Let me see what I can do for it.

**Comment by yapzhenyie** [comment]
> Still present in AdvancedSlimePaper 1.20.1

sorry, GadgetsMenu unable to support AdvancedSlimePaper.

**Comment by BingYanchi** [comment]
> > Still present in AdvancedSlimePaper 1.20.1
> 
> sorry, GadgetsMenu unable to support AdvancedSlimePaper.

![image](https://github.com/yapzhenyie/GadgetsMenu/assets/36477925/4d936d30-378d-43d7-be7a-6102a16bafdc)
In the latest version (GadgetsMenu [Premium] 5.16.0, [AdvancedSlimePaper 1.20.4 - v10 - SRFv12](https://github.com/InfernalSuite/AdvancedSlimePaper/releases/tag/1.20.4-v10-SRFv12)), holograms can be displayed correctly, but miniatures and pets still do not work properly.

```
[00:35:34 WARN]: java.lang.NoSuchFieldException: entityLookup
[00:35:34 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getField(ReflectionUtils.java:378)
[00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getValue(ReflectionUtils.java:446)
[00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:420)
[00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.NMSManagerImpl.spawnNMSMiniature(NMSManagerImpl.java:254)
[00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.miniatures.types.Miniature.lambda$new$0(Miniature.java:55)
[00:35:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[00:35:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[00:35:34 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1654)
[00:35:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[00:35:34 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1533)
[00:35:34 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[00:35:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[00:35:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:35:34 WARN]: [GadgetsMenu] Could not spawn GadgetsMenu miniature!
```

```
[00:36:23 WARN]: java.lang.NoSuchFieldException: entityLookup
[00:36:23 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getField(ReflectionUtils.java:378)
[00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getValue(ReflectionUtils.java:446)
[00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:420)
[00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.pets.entity.utils.SpawnUtil.spawn(SpawnUtil.java:55)
[00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.pets.entity.utils.SpawnUtil.spawnEntityPet(SpawnUtil.java:41)
[00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.pets.Pet.<init>(Pet.java:110)
[00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.pets.PetType.equip(PetType.java:608)
[00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipPet(PlayerManager.java:699)
[00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.menu.menus.PetTypesMenu.onInvClickPetTypes(PetTypesMenu.java:285)
[00:36:23 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor127.execute(Unknown Source)
[00:36:23 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[00:36:23 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[00:36:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:36:23 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[00:36:23 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[00:36:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[00:36:23 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3117)
[00:36:23 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[00:36:23 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[00:36:23 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[00:36:23 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:36:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[00:36:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[00:36:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1450)
[00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1373)
[00:36:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1351)
[00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1235)
[00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[00:36:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:36:23 WARN]: [GadgetsMenu] Could not spawn pet!
```

**Comment by yapzhenyie** [comment]
> > > Still present in AdvancedSlimePaper 1.20.1
> > 
> > 
> > sorry, GadgetsMenu unable to support AdvancedSlimePaper.
> 
> ![image](https://private-user-images.githubusercontent.com/36477925/296594878-4d936d30-378d-43d7-be7a-6102a16bafdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTUzNTIsIm5iZiI6MTcwNTQ1NTA1MiwicGF0aCI6Ii8zNjQ3NzkyNS8yOTY1OTQ4NzgtNGQ5MzZkMzAtMzc4ZC00M2Q3LWJlN2EtNjEwMmExNmJhZmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYzljMGQ1NmEyNGY2NjY0YWNkZjhkNTIzYTAwMTAwYzE0YWFkYTMwZjdhNjkzODQ3MjMxMmY3NmU5MjdlZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jiISSxB_SiqyT86uXM4HUtlrMLfc-o6ACXufeDmDZLU) In the latest version (GadgetsMenu [Premium] 5.16.0, [AdvancedSlimePaper 1.20.4 - v10 - SRFv12](https://github.com/InfernalSuite/AdvancedSlimePaper/releases/tag/1.20.4-v10-SRFv12)), holograms can be displayed correctly, but miniatures and pets still do not work properly.
> 
> ```
> [00:35:34 WARN]: java.lang.NoSuchFieldException: entityLookup
> [00:35:34 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
> [00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getField(ReflectionUtils.java:378)
> [00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getValue(ReflectionUtils.java:446)
> [00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:420)
> [00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.NMSManagerImpl.spawnNMSMiniature(NMSManagerImpl.java:254)
> [00:35:34 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.miniatures.types.Miniature.lambda$new$0(Miniature.java:55)
> [00:35:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
> [00:35:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
> [00:35:34 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1654)
> [00:35:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
> [00:35:34 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1533)
> [00:35:34 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
> [00:35:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
> [00:35:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> [00:35:34 WARN]: [GadgetsMenu] Could not spawn GadgetsMenu miniature!
> ```
> 
> ```
> [00:36:23 WARN]: java.lang.NoSuchFieldException: entityLookup
> [00:36:23 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
> [00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getField(ReflectionUtils.java:378)
> [00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils.getValue(ReflectionUtils.java:446)
> [00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:420)
> [00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.pets.entity.utils.SpawnUtil.spawn(SpawnUtil.java:55)
> [00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R3.pets.entity.utils.SpawnUtil.spawnEntityPet(SpawnUtil.java:41)
> [00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.pets.Pet.<init>(Pet.java:110)
> [00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.pets.PetType.equip(PetType.java:608)
> [00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipPet(PlayerManager.java:699)
> [00:36:23 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.menu.menus.PetTypesMenu.onInvClickPetTypes(PetTypesMenu.java:285)
> [00:36:23 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor127.execute(Unknown Source)
> [00:36:23 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
> [00:36:23 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
> [00:36:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> [00:36:23 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
> [00:36:23 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
> [00:36:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
> [00:36:23 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3117)
> [00:36:23 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
> [00:36:23 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
> [00:36:23 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
> [00:36:23 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
> [00:36:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
> [00:36:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
> [00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
> [00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
> [00:36:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
> [00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1450)
> [00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1373)
> [00:36:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
> [00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1351)
> [00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1235)
> [00:36:23 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
> [00:36:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> [00:36:23 WARN]: [GadgetsMenu] Could not spawn pet!
> ```

Supposing there are 3 lines of holograms, the only one which is working is created using DecentHologram.

Let me see what I can change in order to fix the issues.

**Comment by BingYanchi** [comment]
This issue seems to have been resolved.

Test environment: AdvancedSlimePaper version 1.21.3-16421-dev/1.21.3@1bac93b
