### ISSUE TITLE
spam the console

### ISSUE THREAD

**Issue by games4681** [OnlyNoobDied/GadgetsMenu#957]
**Describe the bug**
your plugin spam my console!!

**Further Information (please complete the following information):**
 - Server Version: 1.20.1
 - plugin version: 5.8.1

**Screenshots**
! [Thu 07:53:35 WARN  GadgetsMenu] Plugin GadgetsMenu v5.8.1 generated an exception while executing task 285475
java.lang.IllegalArgumentException: UUID id cannot be null
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getPlayer(CraftServer.java:632)
    at org.bukkit.Bukkit.getPlayer(Bukkit.java:720)
    at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.hats.animated.AnimatedHat$1.run(AnimatedHat.java:44)
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by games4681** [comment]
You abandoned this github a long time ago apparently.

**Comment by yapzhenyie** [comment]
> You abandoned this github a long time ago apparently.

No, you didn't allow me to answer this issue and you just close it.

**Comment by games4681** [comment]
ok thank you for checking it.
i talking about the premium version of the plugin.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
