### ISSUE TITLE
plugin stop working! - premium version

### ISSUE THREAD

**Issue by games4681** [OnlyNoobDied/GadgetsMenu#962]
the error when i load the plugin:

[15:29:10 INFO]: [GadgetsMenu] Loading server plugin GadgetsMenu v5.13.1
[15:29:10 INFO]: [GadgetsMenu] Enabling GadgetsMenu v5.13.1
[15:29:11 INFO]: [GadgetsMenu] ------------------------------------------------------
[15:29:11 INFO]: [GadgetsMenu]       GadgetsMenu [Premium] 5.13.1 is loading...
[15:29:11 INFO]: [GadgetsMenu]          [server: git-Paper-248 (MC: 1.20.2)]
[15:29:11 INFO]: [GadgetsMenu]                 Running Java 17.0.8.1
[15:29:11 INFO]: [GadgetsMenu]                Plugin by Yap Zhen Yie.
[15:29:11 INFO]: [GadgetsMenu]             Date Modified: 26 October 2023
[15:29:11 INFO]: [GadgetsMenu]                            
[15:29:11 INFO]: [GadgetsMenu]              Initializing module v1_20_R2
[15:29:11 INFO]: [GadgetsMenu] ------------------------------------------------------
[15:29:11 INFO]: [GadgetsMenu] [Economy Storage] Successfully registered economy storage: default (GadgetsMenu)
[15:29:11 INFO]: [GadgetsMenu] [Economy Storage] Successfully set default as the active economy storage.
[15:29:11 WARN]: [GadgetsMenu] Cannot load GadgetsMenu properly, plugin will be disabled. Please contact the author for help.
[15:29:11 WARN]: java.lang.ExceptionInInitializerError
[15:29:11 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.GadgetsMenu.initCosmetics(GadgetsMenu.java:693)
[15:29:11 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:363)
[15:29:11 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[15:29:11 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[15:29:11 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:29:11 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[15:29:11 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:29:11 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:29:11 WARN]:        at PlugManX.jar//com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:421)
[15:29:11 WARN]:        at PlugManX.jar//com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:374)
[15:29:11 WARN]:        at PlugManX.jar//com.rylinaux.plugman.util.PaperPluginUtil.reload(PaperPluginUtil.java:526)
[15:29:11 WARN]:        at PlugManX.jar//com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:125)
[15:29:11 WARN]:        at PlugManX.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97)
[15:29:11 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:29:11 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[15:29:11 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[15:29:11 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[15:29:11 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[15:29:11 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[15:29:11 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[15:29:11 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[15:29:11 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[15:29:11 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[15:29:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:29:11 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:29:11 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:29:11 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:29:11 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[15:29:11 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[15:29:11 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[15:29:11 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[15:29:11 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[15:29:11 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[15:29:11 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[15:29:11 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[15:29:11 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[15:29:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:29:11 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null
[15:29:11 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:148)
[15:29:11 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:659)
[15:29:11 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:60)
[15:29:11 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.nms.v1_20_R2.NMSManagerImpl.setNBTTag(NMSManagerImpl.java:318)
[15:29:11 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.hats.standard.HatType.<init>(HatType.java:314)
[15:29:11 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.cosmetics.hats.standard.HatType.<clinit>(HatType.java:33)
[15:29:11 WARN]:        ... 37 more
[15:29:11 INFO]: [GadgetsMenu] Disabling GadgetsMenu v5.13.1

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
