### ISSUE TITLE
current info about the errlor if you try to load plugin on 1.20.6

### ISSUE THREAD

**Issue by CloudeLecaw** [OnlyNoobDied/GadgetsMenu#971]
```
[23:56:48] [Server thread/INFO]: [GadgetsMenu] Enabling GadgetsMenu v5.16.4
[23:56:48] [Server thread/ERROR]: Error occurred while enabling GadgetsMenu v5.16.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.yapzhenyie.GadgetsMenu.utils.ServerVersion.ordinal()" because "<parameter1>" is null
	at GadgetsMenu_5.16.4.jar/com.yapzhenyie.GadgetsMenu.utils.VersionManager.isSupportDropped(VersionManager.java:36) ~[GadgetsMenu_5.16.4.jar:?]
	at GadgetsMenu_5.16.4.jar/com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:293) ~[GadgetsMenu_5.16.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[23:56:48] [Server thread/INFO]: [GadgetsMenu] Disabling GadgetsMenu v5.16.4
[23:56:48] [Server thread/ERROR]: Error occurred while disabling GadgetsMenu v5.16.4
java.lang.NullPointerException: Cannot invoke "com.yapzhenyie.GadgetsMenu.nms.NMSManager.unregisterPets()" because "com.yapzhenyie.GadgetsMenu.GadgetsMenu.nmsManager" is null
	at GadgetsMenu_5.16.4.jar/com.yapzhenyie.GadgetsMenu.GadgetsMenu.onDisable(GadgetsMenu.java:521) ~[GadgetsMenu_5.16.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by yapzhenyie** [comment]
GadgetsMenu does not support 1.20.6 yet

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
