### ISSUE TITLE
Console error after using CATapult gadget

### ISSUE THREAD

**Issue by krystian987** [OnlyNoobDied/GadgetsMenu#980]
**Describe the bug**
Console error after using CATapult gadget

**To Reproduce**
1. Go to Gadgets -> Mobs & NPCs -> CATapult Gadget
2. Use gadget
3. See error

**Further Information (please complete the following information):**
 - Server Version: Paper 1.18.2
 - GadgetsMenu Version: v5.18.9

Error:
[14:31:17 WARN]: [GadgetsMenu] Task #4019 for GadgetsMenu v5.18.9 generated an exception
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.entity.Cat$Type org.bukkit.entity.Cat$Type.valueOf(java.lang.String)' must be Methodref constant
        at com.yapzhenyie.GadgetsMenu.utils.cosmetics.pets.utils.GOcelotType.getType(GOcelotType.java:38) ~[GadgetsMenu.jar:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetCATapult.lambda$onUpdate$0(GadgetCATapult.java:83) ~[GadgetsMenu.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by yapzhenyie** [comment]
Let me have a look on this issue.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
