### ISSUE TITLE
[Premium] v5.19.0's 1.21.3 support might have broken support for previous versions

### ISSUE THREAD

**Issue by Mitality** [OnlyNoobDied/GadgetsMenu#981]
**Describe the bug**
I have updated a `PaperMC 1.21.1 #131` server from GadgetsMenu [Premium] `v5.18.9` to `v5.19.0`.
This resulted in the plugin no longer enabling:
```
[17:08:15 ERROR]: Error occurred while enabling GadgetsMenu v5.19.0 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be Methodref constant
        at GadgetsMenu.jar/com.yapzhenyie.GadgetsMenu.utils.SoundEffect.<clinit>(SoundEffect.java:1547) ~[GadgetsMenu.jar:?]
        at GadgetsMenu.jar/com.yapzhenyie.GadgetsMenu.cosmetics.pets.types.EntityAllay.<init>(EntityAllay.java:13) ~[GadgetsMenu.jar:?]
        at GadgetsMenu.jar/com.yapzhenyie.GadgetsMenu.cosmetics.pets.TypeManager.initializePets(TypeManager.java:19) ~[GadgetsMenu.jar:?]
        at GadgetsMenu.jar/com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:316) ~[GadgetsMenu.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**API Docs (1.21.1):** [https://helpch.at/docs/1.21.1/org/bukkit/Sound.html#valueOf(java.lang.String)](https://helpch.at/docs/1.21.1/org/bukkit/Sound.html#valueOf(java.lang.String))
**API Docs (1.21.3):** [https://helpch.at/docs/1.21.1/org/bukkit/Sound.html#valueOf(java.lang.String)](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html#valueOf(java.lang.String))

**To Reproduce**
*- explained above*

**Expected behavior**
The plugin should successfully enable on all supported Minecraft versions, not just 1.21.3

**Further Information (please complete the following information):**
 - Server Version: `PaperMC 1.21.1 #131`
 - GadgetsMenu Version: `v5.19.0`

**Screenshots**
![image](https://github.com/user-attachments/assets/4389eaf8-13f8-4842-9467-015ba730f2f3)

**Additional Information**
Don't think anything else is necessary here, if you need more information, feel free to ask

**Comment by yapzhenyie** [comment]
/
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.

**Comment by GG-MD** [comment]
@yapzhenyie 
not fixed

```
[23:26:46] [Server thread/WARN]: [GadgetsMenu] Task #15057096 for GadgetsMenu v5.19.1 generated an exception
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be Methodref constant
	at GadgetsMenu.jar/depend.xxmicloxx.NoteBlockAPI.utils.EnumSound.getSound(EnumSound.java:49) ~[GadgetsMenu.jar:?]
	at GadgetsMenu.jar/depend.xxmicloxx.NoteBlockAPI.utils.InstrumentUtils.getInstrument(InstrumentUtils.java:10) ~[GadgetsMenu.jar:?]
	at GadgetsMenu.jar/depend.xxmicloxx.NoteBlockAPI.songplayer.PositionSongPlayer.playTick(PositionSongPlayer.java:47) ~[GadgetsMenu.jar:?]
	at GadgetsMenu.jar/depend.xxmicloxx.NoteBlockAPI.songplayer.SongPlayer.lambda$start$1(SongPlayer.java:105) ~[GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1770) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1642) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Mitality** [comment]
The issue now no longer occurs on startup, but it still does when trying to use music related gadgets

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.

**Comment by Mitality** [comment]
Yep, works now, tysm! <3

Let me now kindly redirect your attention back to my other, slightly older, issue ([head:OWNER_HEAD doesn't work in player inventories](https://github.com/yapzhenyie/GadgetsMenu/issues/978)) ^^
Steve's head isn't bad, but I'd still prefer my own x)
